### ISSUE TITLE
Multiple OBJECTs per stream with different priorities

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#105]
In the current draft, there's no concept of stream mapping. There's also no limit to the number of messages on a stream, so a sender could send multiple OBJECT messages on the same stream. Each OBJECT message contains a sendOrder indicating the priority.

The problem is that prioritization occurs at the stream level in QUIC. It gets really weird when you share a stream with any OBJECT message.

Here's some examples. The sendOrder of each object is in parentheses. 

- OBJECT (1) + OBJECT (1): This works fine
- OBJECT (1) + OBJECT (2): This requires a QUIC library that can prioritize at stream offsets.
- OBJECT (2) + OBJECT (1): This is impossible.

I think the outcome is pretty clear; messages must only be sent on streams if they share the same sendOrder. We miiiiight be able to support descending priorities but it's difficult in most implementations.

**Comment by kixelated** [comment]
My proposal is to include the priority/sendOrder as a header at the start of every stream.

I would go a step further and say we should have the concept of data streams and control streams like HTTP/3. The first byte indicates the stream type.

- Control streams are alway maximum priority.
- Data streams start with a header (ex. HEADERS) that indicates the sendOrder. There could be one or more payloads that follow (ex. DATA)

This has the side effect of making it easier to parse. I know in my MoQ player, I forward the stream to a decoder thread once I detect an object. That wouldn't be difficult to process if there can be trailing control messages.

**Comment by afrind** [comment]
We've clarified that control messages and objects don't mix.  Do you want to keep this issue open to track the issue with sending multiple OBJECTs on the same stream with different sendOrder?  If so can you retitle and clarify the ask?

**Comment by kixelated** [comment]
> We've clarified that control messages and objects don't mix. Do you want to keep this issue open to track the issue with sending multiple OBJECTs on the same stream with different sendOrder? If so can you retitle and clarify the ask?

Yeah makes sense.

**Comment by afrind** [comment]
In draft-02, you cannot specify multiple objects on the same stream with different priorities.
