### ISSUE TITLE
CDN: Pooling

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#117]
I'm surprised this wasn't filed already.

**Problem**: Within a CDN, there may be hundreds of thousands of simultaneous broadcasts. Establishing a QUIC connection between each node for each broadcast is prohibitively expensive and makes it difficult to coordinate limited resources (ex. congestion control, flow control, prioritization).

Additionally, prioritization works within the context of a QUIC connection. Tracks within the same broadcast MUST be sent over the same QUIC connection in order to be priortized, which means we need some way to force some minimal pooling between specific tracks.

**Comment by kixelated** [comment]
We could take a few different approaches here. 

The first way is to make QUIC connections cheaper. If there was some way to fork a QUIC connection, so the 1RTT handshake can be skipped, then it might be good enough to have a separate connection per broadcast.

The second way is to share a QUIC connection. Each broadcast would need some sort of sandbox to avoid starving each other. This is what WebTransport aims to do with session IDs, although the capsule design is gross.

**Comment by kixelated** [comment]
Regardless of the approach, we need some way of identifying when tracks must be delivered over the same connection and prioritized. A relay needs to know when to create or reuse an existing connection/session for each track.

**Comment by fluffy** [comment]
Agree with the problem and just to put more detail. Many existing CDN have their own ways of distributing the data inside the CDN and my not even want to use QUIC for that at all. What we need to make sure we have is enough data in the transport that the CDN can fairly deal with all this information and make sure that if you look at the CDN as a black box from the outside, the box as a whole has appropriate behavior for all the clients using it. 

As we end up defining our priority scheme, I think it will become clear what information needs to be in the transport such that the CDN black box can provide fair behavior.  That might mean that tracks need a property like priorityGroup if the CDN forwarding is based on something like a sendOrder counter where you can't compare sendOrders from different publishers. 

I feel like as we refine the priority bug, it will become clearer what we need to do with this bug.

**Comment by suhasHere** [comment]
#139 carries some discussions around this.

**Comment by kixelated** [comment]
Closing because there's no action item. Pooling is a massive discussion.
