### ISSUE TITLE
CDN: End-to-end congestion

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#119]
**Problem**: ISPs and transit providers run congested networks. The CDN is able to provide better quality of service by using an uncongested private network. The distance traffic travels outside of the CDN network is colloquially known as "first and last mile".

There's a lot of focus in the industry on first and last mile congestion. This is generally the right approach; WebRTC primarily focuses on the first hop (encoder responds to congestion) while HLS/DASH primarily focuses on the last hop (player ABR in response to congestion).

However there's very little that is done if congestion occurs at an intermediate hop. As a result, CDNs need to over-provision backbone networks to avoid any congestion significantly degrading the user experience. It also rules out transferring media over lossy links, such as between CDNs or between cloud providers.

**Comment by kixelated** [comment]
My proposal is to enable relays to perform congestion response. This means that relays prioritize media and possibly even perform ABR in response to congestion. It should be possible for a CDN to use lossy links and transfer media between CDNs with minimal user impact.

**Comment by fluffy** [comment]
By ABR here, do you mean if their was a high, med, low bitrate stream for the same thing, that transport between relays would priorities med  over high ?  ( if so I agree and I think all the designs have that )

**Comment by kixelated** [comment]
Yeah, prioritizing tracks is one way of performing ABR: "please send me 360p and 720p, preferring 360p if there's congestion".

But I would also like to explore a relay being able to request individual tracks, as requesting all of them will use more bandwidth: "please send me 360p **_or_** 720p, preferring 720p if there's no congestion".

**Comment by wilaw** [comment]
The challenge in chaining together a series of ABR decisions is that the further down the chain you go, the more unstable it becomes. We will need clear signalling to instruct downstream entities that a certain bitrate is being abandoned, otherwise that entity will have hard a hard time separating a temporary delay/gap in data from a permanent switch away.

**Comment by acbegen** [comment]
> Yeah, prioritizing tracks is one way of performing ABR: "please send me 360p **_and_** 720p, preferring 360p if there's congestion".
> 
> But I would also like to explore a relay being able to request individual tracks, as requesting all of them will use more bandwidth: "please send me 360p **_or_** 720p, preferring 720p if there's no congestion".

I don't think this is the right way of doing this. First of all, whatever the upstream relays decide to do will affect everybody downstream (other relays or ultimate receivers). The utility of each track also is different. That is, maybe one track is being consumed by 1M clients as opposed to another one being consumed by only ten clients. How do we expect an upstream relay to do the right thing here? By default, sacrificing several low-concurrency streams for one high-concurrency stream makes sense, or maybe it does not. What I am saying is that if we look at this from a "resource optimization" problem, individual relays cannot possibly make optimal decisions. Rather, CMCD/CMSD type of signaling may be quite useful to help situations like this.

**Comment by fluffy** [comment]
Let me describe something I don't want to have happen then let me propose the direction I think we should go:

Say client P1 publishes to relay R1 that sends to relay R2 that sends to subscriber S2 and subscriber S3. P1 is sending 360P and 720P video. To start with both S2 and S3 have decided to only subscribe to the 720P and everything is going fine with no congestion.  At some point we start to have congestion between R1 and R2. 

What I don't want is a solution where R2 is only getting 720P from R1 to start with, then when the congestion starts, S2 decided to get 360P but S3 stays on 720P and that causes R2 to start getting *both* 360P and 720P from R1. That would not be OK - the response to congestion between R1 and R2 can not be to increase the bandwidth uses between R1 and R2.

There are many ways to avoid this problem. I would favor a simple approach that is not optimal in all cases but works in all cases. Later we can pick a more complicated way.

**Comment by acbegen** [comment]
> What I don't want is a solution where R2 is only getting 720P from R1 to start with, then when the congestion starts, S2 decided to get 360P but S3 stays on 720P and that causes R2 to start getting _both_ 360P and 720P from R1. That would not be OK - the response to congestion between R1 and R2 can not be to increase the bandwidth uses between R1 and R2.

Or, S2 experiences congestion and shifts down to 360p (S3 still stays on 720p) but when R2 starts getting both 360p and 720p, R2 starts experiencing congestion. That might lead to S3 experiencing problems, too. S3 becomes the "loser" in this scenario.

**Comment by wilaw** [comment]
> Say client P1 publishes to relay R1 that sends to relay R2 that sends to subscriber S2 and subscriber S3. P1 is sending 360P and 720P video. To start with both S2 and S3 have decided to only subscribe to the 720P

I think we should architect a distribution system in which a publisher does not send media without being explicitly asked for it. In other words, the scenario described here would not happen, because if S2 and S3 where both subscribing to 720P, then R2 would only subscribe to 720P from R1  and P1 would only publish 720P in response to R1's subscribe.
The reason for this is scale and economics. In a distribution tree of thousands of servers, pushing all bitrates of every broadcast to every node results in a large increase in mid-mile bandwidth, with much of it wasted. With a sufficient subscriber cohort  each node would quickly end up be pulling all bitrates anyway, but at least it would be efficient with every object moving over the network being consumed by an end-subscriber.

For those who want the "instant on" effect you can achieve for end-subscribers by pushing all content to the edge relay, it can be delivered by having agents who subscribe to bitrates on the true subscribers behalf. These agents can seed the edge network cache ahead of end-subscriber demand. This creates an instant-on effect without breaking the simple tenant of "don't publish until you get a subscribe".

**Comment by kixelated** [comment]
I agree with Cullen. I don't want a situation where a relay MUST receive all renditions in order to operate. Leaving the choice of rendition solely up to the end viewers means the CDN cannot be flexible in response to congestion.

We should assume that relays may be congested. I love Victor's example of a CDN edge on a cruise ship. The last "mile" is flawless, while the congestion primarily occurs in the hops between relays (ship to satellite).

**Comment by gwendalsimon** [comment]
> I think we should architect a distribution system in which a publisher does not send media without being explicitly asked for it. In other words, the scenario described here would not happen, because if S2 and S3 were both subscribing to 720P, then R2 would only subscribe to 720P from R1 and P1 would only publish 720P in response to R1's subscribe. 

I am not sure the definition of "publish" is clear here. It can mean 1/ publicly announcing that multiple qualities are available, 2/ encoding and packaging all these qualities, in the case anyone subscribes to it, 3/ sending all qualities to the relay that subscribes to any of these qualities. 

In most of today's ABR systems, the origin server does 1 and 2 but it does not 3.  It would indeed by weird to waste network resources for unrequested contents. Some systems also implement Just-in-Time (JIT) systems to do 2 only upon request, with the same argument that it would be weird to waste CPU/GPU resources for unrequested content.

Anyway, here the publisher "announces" that it can do bot 360p and 720p, It may be not "sending" both streams to R1 at the beginning of this use case but, if S2 starts requesting 360p while S3 still requests 720p, then both subscriptions will arrive to the P1. who will then "send" both streams.

**Comment by kixelated** [comment]
Going to close this because there's no action item and it's better suited for a requirements draft. I do think ABR over the backbone is useful, but kind of difficult to implement. Either way it should be in it's own issue.
