### ISSUE TITLE
CDN: Routing

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#120]
Related to #118 

**Problem**: CDNs serve a huge number of broadcasts, far more than can reasonably fit on every edge host. The solution in the HTTP world is to fetch content on demand on a cache miss. These cache misses are expensive compared to a cache hit (fetches from upstream), so there's incentive to minimize the number of hosts that are eligible to serve specific content in order to maximize the cache hit ratio.

This significantly complicates routing. Viewers need to subscribe to eligible edge nodes which need to subscribe to eligible relays over the backbone. At least within Twitch, there's an dedicated service to determine this eligibly on a per-host and per-datacenter basis.

It's also difficult to determine the best path to an origin. Network routing protocols are typically pretty good at this but operate at the IP layer (L3), requiring some form of application routing (L7) in order to perform deduplication and caching (exception: multicast). This is further complicated by the fact that L7 caching/routing may use more resources than it's worth (ex. 1 viewer broadcasts) and L3 routing may be desirable for specific hops.

**Comment by kixelated** [comment]
My proposal is to leave routing up to the application and CDN. Frankly it's just too difficult to prescribe anything. A URL schema could be justified (ex. emitter domain in first part of the path) but I don't think it's sufficient to replace application-defined routing.

**Comment by wilaw** [comment]
I concur on leaving routing within a distribution network (CDN) up to the CDN. CDNs will compete on how to best route MoQ traffic and that optimality is a function of their network topology, network resources (memory, compute, connectivity) and competing loads. It is dynamic in nature and different for each network. 

What MoQ does need to standardize are consistent identification, addressing and authorization schemes for content, as well as propagation of prioritization intent. The routing itself should be left to the deploying entities.

**Comment by acbegen** [comment]
There are many other things that might affect the routing decisions and we cannot possible describe all the possible ways or the best way of doing it. So, yes, this responsibility falls to the CDNs - not MOQ WG.

**Comment by fluffy** [comment]
Agree - what we need to have in MoQ is simply the info that CDN need to determine routing. From a requirements point of view I think that means: info to authorize and bill for a pub or sub. For pub, the upper bound on the desired time to live of for the object. Of course the CDN might kill the object much sooner but if they are billing for storage, it is nice for the client to set an upper bound.

**Comment by afrind** [comment]
The Announce proposal (#150 / #123) is related to this issue.  I don't think it's intended to replace intra CDN routing, inter-CDN routing or CDN-to-static-origin routing, but attempts to solve the distributed publishing/dynamic origin case.

**Comment by nikolay167** [comment]
Hey!

We are a CDN provider, And we also have support of QUIC.

If want to test anything dont hesistate to let me know :)

**Comment by fluffy** [comment]
We seem to be on agrement on this and matches the daft. Can we close it ?
