### ISSUE TITLE
Add support for unsubscribe on tracks

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#132]
As pointed about by @afrind  https://github.com/kixelated/warp-draft/pull/122#discussion_r1160819780, it useful to have explicit unsubscribe on tracks. 

This will come in handy across these flowsl
1. Client has subscribes to HD quality and it wants to get to SD quality and is not interested in HD quality anymore
2. Client is no longer interested in certain tracks being published and wants to unsubscribe only those tracks

**Comment by kixelated** [comment]
+1

**Comment by fluffy** [comment]
Just to add details from the call. I heard people say we needed all of:

1. Way for server or relay to end a subscription and let the client know 
2. Way for the client to end 

I will add in a slight detail that when we do get around to adding this to the draft, we want to consider the sequencing of ending a subscription and starting a new one. If a client is subscribed to HD and wants to move down to SD for lack of bandwidth reasons, we do not want a situation where both HD and SD are being sent for extended times during the transition.

**Comment by VMatrix1900** [comment]
+1. Client should be able to end the subscription of a track.

**Comment by fluffy** [comment]
So to start discussion on this ....

if A subscribes to B, we need a few things:
1) a way for A to stop that subscription B
2) a way for B to stop the subscription 

What I don't want is if A makes a single subscribes to B for a specific set of objects, to be able to unsubscribe for some of those objects but not all. If A wants to that, it needs to end stop the first subscription and at same time start a new subscription for the subset of objects.

**Comment by kixelated** [comment]
Going to flag this as a blocker because you can't implement client-side ABR or track selection without it.

**Comment by kixelated** [comment]
Proposal mirror QUIC's `STOP_SENDING`.

```
SUBSCRIBE_STOP Message {
  track_id (i),
  error_code (i)
}
```

This assumes the receiver chooses the `track_id` to fix #145. Otherwise, there's a race condition pending receipt of `SUBSCRIBE_OK` so you need the full name:
```
SUBSCRIBE_STOP Message {
  track_namespace (b),
  track_name (b),
  error_code (i)
}
```

The sender would still need to issue a `SUBSCRIBE_ERROR` to officially terminate the subscription, mirroring QUIC's `RESET_STREAM` and effectively acting as an acknowledgement. Otherwise it's not valid to issue an identical `SUBSCRIBE` (ex. reusing the `track_id`) until this message is received otherwise as it causes race conditions (can elaborate).

The error code is somewhat useless in `SUBSCRIBE_STOP` just like `STOP_SENDING`, but it might be useful for some applications. It's mostly there to be echoed by the `SUBSCRIBE_ERROR`. I'm perfectly fine removing this error code and registering a "cancelled by peer" code instead.

**Comment by kixelated** [comment]
> if A subscribes to B, we need a few things:
> 
> 1. a way for A to stop that subscription B
> 2. a way for B to stop the subscription

As proposed above:
1. A issues `SUBSCRIBE_STOP`, causing B to issue `SUBSCRIBE_ERROR` with the provided error code.
2. B issues `SUBSCRIBE_ERROR`.

**Comment by suhasHere** [comment]
#203 has a proposal on the same too .. copying the text for reference here. I think these are closely related 


We need few things in general between announcements and subscriptions

1. Cease the announcement

```
ANNOUNCE_CEASE {
  Track Namespace
   ....
}
```

This is an explicit signal from the publisher that it is no longer interested 
in sending media for the announced tracks.  This is sent to the relay to trigger subscription cancellation downstream and clean up local relay state.

2. Terminate the Subscription

```
Subscribe Terminate {
  Track Namespace
   Reason { ..... }
}
```
Subscribe Terminate can be sent to indicate the subscription is stopping and  each receiving entity will forward the same to downstream and clean up local subscription state. If it is the consumer, it stop media pipeline and so on.


3. Unsubscribe
For subscribers to explicitly indicate that they are no longer interested in a given track , they will send

```
Unscubscribe {
Track Namespace
....
}
```

**Comment by afrind** [comment]
UNSUBSCRIBE / UNANNOUNCE is in the draft now, and we're going to add a SUBSCRIPTION END/FIN (#203).  

@suhasHere Can this be closed?
