### ISSUE TITLE
Messages during handshake

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#136]
It's unclear what messages are allowed to be sent or received during the SETUP handshake. Here's my intuition:

Until receiving the SETUP, the **client**:
1. MUST NOT send messages
2. MUST buffer any received messages.

Until receiving the SETUP, the **server**:
1. MUST NOT send messages.
2. MUST NOT receive messages.

The client needs to buffer messages because the server is unaware of when the client receives the SETUP. There's no equivalent to HANDSHAKE_DONE, and adding something like that would add an RTT anyway.

**Comment by kixelated** [comment]
A potential optimization exists if the message encoding if the same for all supported versions (invariants). For example, if the client only advertises support for versions 1,2,3 and those versions share the same SUBSCRIBE encoding and meaning. This seems unlikely, given a separate version was created in the first place, and seems very brittle.

If this was the case, then the client could process any invariant messages immediately and buffer the others. However, the client still couldn't send messages unless the server buffered any received messages.

**Comment by vasilvv** [comment]
The most flexible optimization would be the one where you could encode the SUBSCRIBE_REQUEST for every version you offer as a field in SETUP parameters.  TLS does not do exactly that, but there are some things in ClinetHello that are only applicable for certain versions.
