### ISSUE TITLE
Rename the protocol

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#142]
During authors call, it was agree to use `moq-transport` as the name for the protocol.

**Comment by suhasHere** [comment]
I can propose a PR on this change . any thoughts?

**Comment by afrind** [comment]
Let's hold off until the outstanding PR list is close to 0 to prevent heinous merge conflicts.  You have several stale PRs you can close.

**Comment by kixelated** [comment]
I like `moq-transport` for the generic pub/sub transport. 

But I don't know what we should call the media document that Will is working on. I propose `moq-media` although it's redundant if moq is an acronym...

**Comment by kixelated** [comment]
And yeah, let's rename the draft as part of the PR that removes all references to media.

**Comment by fluffy** [comment]
The redundancy of moq-media does not bother me. I like the simplicity of moq-transport (which is not a transport) and the moq-media (which is nuts if you expand the acronym). They will make it easy for people to google for what they are looking for and understand what they are likely to find in the draft.

**Comment by afrind** [comment]
I want to close this issue because #197 landed, but I think there's some agreement that we want to keep iterating.

**Comment by ianswett** [comment]
I am going to close this for now, but it can be re-opened if there are strong opinions.
