### ISSUE TITLE
Who creates the Catalog in an ingest case 

### ISSUE THREAD

**Issue by fluffy** [moq-wg/moq-transport#144]
I think people are imagining different things for how the catalog is created. 

As an example to motivate this, a generic OBS client used for ingest with a 4K camera could generate video at many different resolutions yet the application it is sending the video to can probably only use a handful of different resolutions. For example, webex could accept a main video stream at say 3 different resolutions or a content share stream at 4 different resolutions. (this is an over simplification of webex for this example).  Webex can not transcode in cloud if is doing E2E encryption. The OBS client needs some way to find out what video resolution are acceptable, and can then send this.  

The key issue is that the generic client needs to know what the application wants, and it gets that via the Catalog. The applications not the generic client needs to create the catalog. This is how it works in the subscription case and I am proposing how that it should work the same way in the ingest case. 

In RTMP the server would send the Invoke message to tell the the OBS client what to do. If we want MOQ to be a replacement of RTMP, we need some functionally like this. 

My proposal for how this work is the webex cloud site gets a catalog to the client in one of two ways. It can send it out of band in some HTTP before things start, or it can provide a URL where the OBS client can subscribe to the catalog. 

Given how much is already implemented, I feel like I might be missing something in my understanding  of how this would work if the generic OBS client created the catalog. Very open to any solution to this problem.

**Comment by kixelated** [comment]
Thanks for recognizing the disconnect. The encoder must create the catalog unless there's a sophisticated capabilities exchange. 

The main reason being is that the catalog contains encoding parameters, such as codec, profile, resolution, bitrate, etc. The ingest server can't just tell the generic broadcast client (ex. OBS) what to encode, because it may not be supported or feasible. This is especially important when hardware encoding and low-powered devices are involved.

**Comment by kixelated** [comment]
There was some discussion about media capabilities in #5. I do think there's a lot of overlap between announcing tracks and announcing capabilities. (ex. SDP...)

**Comment by fluffy** [comment]
I get the example of some hardware encoder on a mobile phone is going to range of quirks but I will note that with WebRTC, we found these were far less than people thought they would. But agreeing with example use case you are raising. 

I was thinking the catalog would say  send me H.264 720P30 at 1.5 Mbps  and then in the init segment for the track, it would have "AVC baseline profile 4:2:2 Level 3.2 but using CABAC"

**Comment by suhasHere** [comment]
> Thanks for recognizing the disconnect. The encoder must create the catalog unless there's a sophisticated capabilities exchange. 
> 
> 
> 
> The main reason being is that the catalog contains encoding parameters, such as codec, profile, resolution, bitrate, etc. The ingest server can't just tell the generic broadcast client (ex. OBS) what to encode, because it may not be supported or feasible. This is especially important when hardware encoding and low-powered devices are involved.

I suspect we are trying to solve a specific application level problem at the transport level. Having capabilities exchange is fine (it will be the case for all real-time flows, probably true for other usecases too) and can be defined elsewhere. 

The only invariant here is - publisher has list of tracks (say from catalog) and based on that it can either request to publish or in some closed scenarios start sending media objects ( which is again application choice) 

We need to support protocol semantic for the above. #123 is a start place for that.

**Comment by kpugin** [comment]
> In RTMP the server would send the Invoke message to tell the the OBS client what to do. If we want MOQ to be a replacement of RTMP, we need some functionally like this.

To be fair, that's not how Meta RTMP ingest works, I wonder if Twitch or Youtube use RTPM Invoke?

**Comment by kpugin** [comment]
> The OBS client needs some way to find out what video resolution are acceptable, and can then send this.

I agree, this is a problem and in the past we tried to work with OBS folks on some sort of API that would allow server to "configure" OBS encoder, unfortunately it didn't go far enough. Putting this "configuration API" inside of MoQ protocol as @fluffy proposing sounds like good idea. I wonder, though, if that needs to be part of MoQ spec or it can be out of band protocol?

**Comment by fluffy** [comment]
Yah, this thread has made this all clearer to me. I was blurring the configuration "figure out what to send" and the "say what you are sending".  I think you are convincing me that a catalog is simply a report of what is being sent and is not part of of the figuring out what to send.

**Comment by afrind** [comment]
@fluffy is this good to close then?

**Comment by fluffy** [comment]
I think there is still a bunch of stuff to be sorted out on this but it is starting to get covered in the drafts and I don't think we need this issue anymore. I would propose close this.

**Comment by afrind** [comment]
Closing per @fluffy
