### ISSUE TITLE
Discontinuities

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#15]
There's currently no way to reset the timescale. This is very useful when stitching in content, as the new media could start at PTS 0 but still appear continuous. Otherwise the server would need to rewrite the media timestamps. Discontinuities are also used to reset the decoder, although I'm not sure what else it impacts other than the timestamp.

A discontinuity flag for each layer wouldn't work since layers arrive out of order. In order to support discontinuities, you need to know the last timestamp+duration, which may not have arrived yet.

A possible solution is to include `baseTimestamp` in each layer, indicating the decoder should add this value to each timestamp. The only problem is that it would be a little annoying to repeat the base timestamp for each layer. Maybe the base timestamp could be inherited by dependency layer(s)? Not sure.

**Comment by vasilvv** [comment]
I suggest that we have an "epoch" counter.  You start with epoch = 0, and then increment it by one every time you want to reset the timestamps.

We may also want to tie init segments (#21) to the epoch?  E.g. if you want to switch the resolution mid-stream, you would probably want to reset the decoder and add new video format metadata anyways.

**Comment by kixelated** [comment]
Yeah that's my thought as well.

**Comment by fluffy** [comment]
Hmm - I'd think it would be a good idea to sketch out a few design on this and get better idea of all the issue. I lean towards something that is mappable to real ntp time so that things can be debugged as well as synchronized. (note "mapped to" leave open a wide range of possible solutions including probably what you were talking about above )

**Comment by kixelated** [comment]
I definitely want some way to map PTS to wall clock timestamp as well.

**Comment by kixelated** [comment]
Still needs discussion, but most definitely part of the streaming format draft.
