### ISSUE TITLE
ROLE doesn't support negotiation

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#151]
The SETUP message contains a ROLE parameter. In the current draft, the client specifies the value, indicating if the client will send data (0x1), if the server will send data (0x2), or if both endpoints will send data (0x3).

A conferencing client supports the ability to send and receive media, and would always send role=0x3 because it supports both functionalities. However, it's unaware of the server functionality, and the server has no way of informing the client if it intends to send media. This matters because a generic client needs to know if it shows a black screen and/or should send a SUBSCRIBE message (ex. for /catalog).

I propose that both endpoints send the ROLE parameter: 0x1 = publisher, 0x2 = consumer, 0x3 = both. This gives the server the ability to specify its own functionality.

**Comment by suhasHere** [comment]
I am not very sure why do we even need Role in the first place .. can it be changed mid-session ?

Say the use-case
- Participant in media conference joins as subscriber only since he is driving and want to listen in
- Then at some point mid session , he wants to contribute and he now becomes as publisher and subscriber

what is the expected flow in this case ?

**Comment by kpugin** [comment]
Current draft doesn't really explain what ROLE parameter is for, only that client needs to send it - what was original idea? Why not just always allow everyone to send and receive data?

**Comment by kixelated** [comment]
I think ROLE is good for negotiating half-functionality.

- If the remote endpoint cannot send media (ex. player), then sending a SUBSCRIBE is invalid.
- If the remote endpoint cannot receive media (ex. OBS), then sending a ANNOUNCE/OBJECT is invalid.

@suhasHere brings up a good point. If an endpoint _could_ switch roles, then it should advertise full functionality. That would include publishing an empty catalog so it can append it later if it wishes to actually publish tracks.

**Comment by fluffy** [comment]
I don't think I seem much use for the Role - it seems like something the application would know at a higher layer. But I have no objection to including it if others do see a need for it. It's not like it makes life harder for applications that don't use it.

**Comment by VMatrix1900** [comment]
If the ROLE is used to enforce the half-functionality, then it needs to be clear what should be done when invalid message is received. Sending a GOAWAY? Sending a generic error message? Does the connection need to be terminated? I think most of the time, application will just choose the full functionality in case of role switching on the fly and avoid the invalid response code(just ignore the invalid message).

**Comment by kixelated** [comment]
Oh hey, I found a good use-case for ROLE.

If my client connects with ROLE=publisher, then the server knows that it should not send ANNOUNCE messages. The messages are useless and actually triggered a deadlock in my broadcaster, since the application was not reading them and overflowed the receive channel.

I like the ability to specify half-functionality.
