### ISSUE TITLE
Refactor to have general publisher/subscriber section

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#153]

**Comment by fluffy** [comment]
The easiest to review diffs on a change like this is if we did one PR that did not add or delete any text but only moved it. Then after that a PR that made the changes to text to fix up the text to make sense in after the move. We did when writing the JSEP draft and it made things way easier to review.  

I am hoping the relay section is super short.

**Comment by ianswett** [comment]
Given there are adjacent sections about publisher and subscribers, I'm going to close this unless there's an issue that needs fixing: https://github.com/moq-wg/moq-transport/blob/main/draft-ietf-moq-transport.md#subscriber-interactions
