### ISSUE TITLE
Proposal: Full Track Name to include emitter information

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#154]
As part of the announce message discussions, there has been discussions around using shortest common prefix to announce rather than listing all the tracks to keep the CDN table updates performance under control. 

See Will Law's comment at https://github.com/kixelated/warp-draft/pull/123#discussion_r1188892031

The proposal is to extend Full Track Name to include reference to Emitter who is responsible for publishing the media as defined below

If we have full track name defined as 
```
Full Track Name = Track Namespace + "/" + Emitter Id + "/" + Track Name
```
where emitter  is something like defined in https://datatracker.ietf.org/doc/html/draft-nandakumar-moq-arch-00#section-2.1.1

In that case Announce is defined as 

```
Annouce {
   Track Reference,
   [Params]
}
```
where Track Reference is

```
Track Reference = Track Namespace + "/" + Emitter Id
or 
Track Reference =  Full Track Name

```

The same can be extended to Subscribes too, however to support granularity on subscription start point, one need to do it a the track level using Full track Name, which seems to be fine too.

```
Subscribe Request {
  Track Reference,
  Params
}

```

**Comment by afrind** [comment]
Commenting as an individual:

Is either the namespace itself or the emitter ID used by the transport, or is a prefix string match sufficient at this level?  If either or both are required, then I prefer sending them as structured data rather than a string whenever possible, since it avoids having to parse out the bits.

**Comment by afrind** [comment]
Has the consensus around track naming in #162 resolved this @suhasHere, or would you still like to see Emitter explicitly in FTN?
