### ISSUE TITLE
Document full contribution and distribution flow

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#159]
Here's what I think the full flow looks like. It hasn't been explicitly stated, and maybe that's the source of some disagreements.

### Step 1 - Producer configuration
A producer (ex. OBS) is given a few pieces of information:
- `connect_url`: Used to establish the WebTransport/QUIC connection.
- `track_namespace`: Used to identify the broadcast.
- `auth`: Any authentication details that need to be provided.

### Step 2 - Producer catalog
The producer creates a catalog that contains any number of tracks. Each track has:
- `track_namespace`: (optional) if not provided, the track inherits the catalog namespace.
- `track_name`: This is specific to the application (ex. "audio", "video_480p", etc).
- `media_properties`: Indicates how media is encoded, and how tracks are related to each other.

### Step 3 - Producer connect
The producer establishes the QUIC connection to the provided `connect_url`.

### Step 4 - Producer announce
When it is ready, the producer sends an ANNOUNCE containing: 
- `track_namespace`
- `auth`

The server replies with ANNOUNCE OK. The broadcast is now ready for consumption.

### Step 5 - Consumer configuration
A consumer (ex. VLC) is given a few pieces of information:
- `connect_url`
- `track_namespace`
- `auth`

### Step 6 - Consumer connect
The consumer establishes the QUIC connection to the provided `connect_url`.

### Step 7 - Consumer catalog
The consumer issues a SUBSCRIBE for the catalog:
- `track_namespace`
- `track_name`: `catalog` or `/` (TODO)
- `auth`

### Step 8 - Relay routing
Any intermediate relay (optional with peer-to-peer) will route the SUBSCRIBE to the publisher. SUBSCRIPTIONS may be deduplicated and cached if the relay is able to perform authentication.

The producer replies with a SUBSCRIBE OK and transmits OBJECTs for the requested track. The OBJECTs flow back over the same connection as the SUBSCRIBE until they reach the consumer(s).

### Step 9 - Consumer parses catalog
The consumer receives the catalog and parses it. For each track, it learns:
- `track_namespace`
- `track_name`
- `media_properties`

### Step 10 - Consumer subscribe
The consumer issues a SUBSCRIBE for each track it would like. These flow to the publisher and back as described in step 8.

**Comment by afrind** [comment]
This is very helpful and matches my understanding of what is in the draft.

**Comment by afrind** [comment]
Should we move this to a wiki or something?

**Comment by afrind** [comment]
I'm closing this issue as it doesn't represent something that needs to change right now.
