### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#16]
We're using WebTransport to establish the connection, which uses a HTTP CONNECT request. Is rejecting this CONNECT request enough for authentication or do people want an explicit message?

**Comment by kpugin** [comment]
Let's not do auth, client will get WebTransport url from somewhere - that part can take care of "auth"

**Comment by suhasHere** [comment]
Some form of auth mechanism (say token) is needed for relays/edge nodes to authorize publishes and subscribes.
How such a token is obtained is out of scope for MOQ , but the protocol needs a way to provide the auth info before sending or receiving the media

**Comment by wilaw** [comment]
Reviewing this older thread per discussions at last week's editors call. Two issues regarding authentication need to be resolved:

1. Do we have consensus that an auth mechanism (such as tokens) is out of scope for Moq-transport ?
     2. Argument For: there are many possible means to authenticate and defining one (or a few) limits the flexibility of implementers in adopting the newest auth mechanism, thus inhibiting innovation.
     3. Argument against: for the broadest interop, it would be useful to define a baseline authentication mechanism which all implementations must support. This does not stop implementers in adding additional authentication methods. 
5.  How should auth be communicated with a raw QUIC connection, in which no CONNECT equivalent is available? Should space be reserved in the PATH parameter per https://kixelated.github.io/warp-draft/draft-lcurley-warp.html#native-quic for a token? Is the format of this left to the implementers, or should moq-transport define a baseline implementation?

**Comment by afrind** [comment]
The current draft allows for auth to happen in a number of places:

1. At the TLS layer when establishing the connection
2. During the CONNECT step for WebTransport or PATH SETUP parameter for raw QUIC
3. When sending ANNOUNCE or SUBSCRIBE

Do we need more points to carry auth or can we close this for now?  There's also issue #152

@kixelated

**Comment by kixelated** [comment]
I think we need more sophisticated authentication, which is why I filed #152. A byte blob in the SUBSCRIBE/ANNOUNCE sucks for interoperability and it doesn't support challenges (public key crypto). If we're going to add an authentication layer to MoQ (number 3 in Alan's message), it needs to be more fleshed out.

But I also don't really care and this issue is too broad, so CLOSED.
