### ISSUE TITLE
Negotiation

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#18]
How do we negotiate which codecs, resolutions, bitrates, etc that an endpoint is willing to support?

SDP sucks please don't suggest it.

**Comment by kixelated** [comment]
Also we should have a way to negotiate the container format.

**Comment by suhasHere** [comment]
QuicR has a simple manifest to declare/advertise  (not negotiate and hence no SDP ;) ) the capabilities . That would be one way to do and the same can be solved otherways too .

Some starting notes here: https://www.ietf.org/id/draft-jennings-moq-quicr-proto-01.html#name-quicr-manifest

**Comment by vasilvv** [comment]
I feel like there are three related problems here:
1. A sender needs to describe what it is going to send
1. A receiver needs to describe what it is willing to accept
1. Two of those parties might need to have an algorithm to come to an agreement regarding the best way to exchange media.

I believe that the first one should be always required and we should have a uniform way of doing that.  The second one is optional though useful (e.g. as a live encoder I will send H.264 by default, but will upgrade to more recent codecs if offered support), but it is also harder (e.g. for problem one, you just say "I am sending stereo", for problem two, you need to say things like "I accept both mono and stereo").  The third one feels like it belongs on a higher level protocol/system.

**Comment by kixelated** [comment]
This is the catalog.
