### ISSUE TITLE
Relay send while receiving

### ISSUE THREAD

**Issue by jordicenzano** [moq-wg/moq-transport#205]
Should we mention that a relay should start sending object as soon as the object can be identified (after the header)?

Since the draft points out latency as a big deal, it seems this is a must have if we want to cover ULL cases

**Comment by VMatrix1900** [comment]
+1.

**Comment by kixelated** [comment]
It used to be in #148 but was removed: "A sender SHOULD transmit incomplete objects to avoid incurring additional latency."

I think [this was the conversation](https://github.com/moq-wg/moq-transport/pull/148#discussion_r1178341564) and the agreement was to put it into some non-existent latency section.

**Comment by suhasHere** [comment]
+1 We should add a recommendation text for Relays to address the request from @jordicenzano
