### ISSUE TITLE
What about live rewind or VOD use cases

### ISSUE THREAD

**Issue by jordicenzano** [moq-wg/moq-transport#207]
With sentences like "The publisher MUST start delivering the objects from the most recent group" seems the the draft is only considering live edge for now. But perhaps we would want to tackle other cases like "rewind" or "VOD", those will probably add more complexity on the server side.

Just some thoughts:
- To tackle more use cases than live edge I think we should add timing information somewhere, and that info should be readable by the relay. If we do not have that, how the relay knows
    - Which objects start sending and when to send them?
    - How to align different tracks (ex: audio and video)

**Comment by VMatrix1900** [comment]
Rewind or VOD can be implemented by setting the GROUP SEQUENCE Parameter and OBJECT SEQUENCE Parameter. And it will not add complexity on the server side since it is client driven.

**Comment by ianswett** [comment]
Related to #245

**Comment by ianswett** [comment]
Closing this as being subsumed by #245.
