### ISSUE TITLE
Naming: Track ID or Subscription ID or ?

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#209]
I'm implementing moq-transport-00 now and ran into this. I thought we decided on a course of action but we must have gotten distracted with the actual important changes.

### Problem
The `track ID` contained in the SUBSCRIBE OK message is used to map the full track name into an varint. However, as explained in #145, there's a race condition when the SUBSCRIBE OK message is delayed. OBJECTs will arrive and the receiver will have no idea what track they're for and will have to buffer them.

### Proposal
Move the `Track ID` from the `SUBSCRIBE OK` message to the `SUBSCRIBE` message. This moves the responsibility for choosing an ID from the sender to the receiver. The benefit is that a receiver never has to buffer OBJECTs waiting for a SUBSCRIBE OK, and can instead abort/discard unknown OBJECTs. The downside is that the sender has to use a different `Track ID` for each connection.

`Full Track Name` would be removed from `SUBSCRIBE OK` and `SUBSCRIBE ERROR` since it would be redundant.

**Comment by suhasHere** [comment]
I personally don't see the naming is confusing in this case. Its still an alias for the track requested and it does indeed represents the track.

It may be good to split this in to 2 /3 issues . One for if we should rename and another on how an alias is generated and proposals to change the message (OK/ERROR) ??

**Comment by kixelated** [comment]
> I personally don't see the naming is confusing in this case. Its still an alias for the track requested and it does indeed represents the track.

Is the `track ID` a property of the track? You can argue "maybe" when the sender chooses the ID, but it's a definitive "no" when the receiver chooses and it will be different for every connection. Meanwhile, the `track full name` is a actually property of the track, and it is by definition the unique identifier (ID) for a track within a scope.

But it's just a name so it's fine to leave as is. The rename will make more sense as we flesh out more subscription mechanisms like server-side ABR.

**Comment by kixelated** [comment]
Here's how the flow would work if we add #132:
```
SUBSCRIBE   id=4 name=twitch.tv/kixelated/480p
UNSUBSCRIBE id=4
SUBSCRIBE   id=5 name=twitch.tv/kixelated/720p
UNSUBSCRIBE id=5
SUBSCRIBE   id=6 name=twitch.tv/kixelated/480p
```

I think it's confusing that `track_id=4` and `track_id=6` actually refer to the exact same track. That's why I claim it's a subscription identifier, and not a track identifier.

And if we explicitly call it a `Subscribe ID`, then updating subscriptions becomes valid. I'm not sure if this is explicitly a good idea, but it would be nice for seamlessly switching between tracks at group boundaries. Otherwise the receiver has to guess the most recent group ID when switching between renditions.

```
SUBSCRIBE id=4 name=twitch.tv/kixelated/480p
SUBSCRIBE id=4 name=twitch.tv/kixelated/720p
```

**Comment by suhasHere** [comment]
SUBSCRIBE id=4 name=twitch.tv/kixelated/480p
SUBSCRIBE id=4 name=twitch.tv/kixelated/720p

--> this will never work. You can't have 2 different tracks to have same trackId of 4. This is just a wrong implementation.

In the example
```
SUBSCRIBE   id=4 name=twitch.tv/kixelated/480p
UNSUBSCRIBE id=4
SUBSCRIBE   id=5 name=twitch.tv/kixelated/720p
UNSUBSCRIBE id=5
SUBSCRIBE   id=6 name=twitch.tv/kixelated/480p
```

once id=4 is unsubscribed, the implementation need to clean up the context. When a new subscribe for the same name happens and get id=6, its the new alias for the same track.

I still don't see why renaming is making anything less or more clearer. Its just an alias for an active track.

Again we are mixing 2 issues here - one renaming and another where the Id should be generated (in subscribe or subscribe_ok) .

**Comment by afrind** [comment]
+1 to Suhas that what we call it and how it works are different issues.  Is this issue only to discuss naming and we can use 145 to discuss behavior?

**Comment by kixelated** [comment]
Sorry, I shouldn't have posted that example. I didn't even explain the problem it was trying to solve, and we can discuss that in a separate issue.

Let's leave the name.

**Comment by kixelated** [comment]
And thinking about it some more, I've been calling it "subscription ID" in my code mostly because "track ID" is already used by CMAF. One is a transient varint chosen by the subscriber scoped to the connection, and one is an int32 chosen by the encoder scoped to the catalog.

**Comment by fluffy** [comment]
It seems like a more stateless relay design would be better where if two subscriptions from different clients subscribed to the same track, the relay had the option of using the same ID for both of them. Not all relays would do this but it seems like some would want to be that way to map up with existing CDN implementations. Not sure what I think but definitely needs some brainstorming.

**Comment by ianswett** [comment]
To make it clear that this issue will focus on naming, per Alan's suggestion, I retitled it and marked #145 as architectural

**Comment by ianswett** [comment]
I believe this is likely OBE, but we can put it into the Subscribe category for Prague, particularly around having multiple simultaneous subscriptions.

**Comment by afrind** [comment]
I think this issue was only tracking what to call Track ID -- isn't it still terminology?

**Comment by afrind** [comment]
As for naming, Track Name Alias was the most recent suggestion to replace Track ID.

**Comment by afrind** [comment]
I think the group has settled on Subscription ID (identifies a subscription) and Track Alias (identifies just a full track name) for now.
