### ISSUE TITLE
Init segments

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#21]
HLS and DASH both have a concept of init segments when using fMP4. The init data could be prepended to each segment, but it's more efficient to transfer it once and have each segment reference it.

The current draft supports init segments via the `depends` property. At first glance this seems like an okay way to reuse the property, as it's probably needed for SVC and frame-based delivery. The use case is slightly different though, as init segments MUST be received in their entirety while SVC layers and frames need to be interleaved.

The two big issues that I see are:

1. The ability to cache init segments for an undisclosed amount of time. It's not a lot of data so we could probably put a `cache: forever` field, but it needs to be a requirement.
2. CMAF encoding is different. Init segments use ftyp/moov/mdat while other segments use styp/moof/mdat. It's not a huge deal but it does make it seem like init segments should be first class citizens in the draft, rather than something added on.

**Comment by kpugin** [comment]
init segments are going to create problems:

- It introduces "artificial" dependency, so any decoder will have to receive them before they are able to decode any segment
- if there is transcoder in the middle, they would need to be aware of "init" segment, which can be a problem when reconnect happens on ingestion side.
- this doesn't support codec switch in the middle, at least not easily...

**Comment by kpugin** [comment]
What if we don't require init segments? And just require every "Segment" to have information needed for decoder, for h264, for example, have SPS/PPS, for audio segment, have AudioSpecificConfig for every audio segment

**Comment by kixelated** [comment]
HLS used to do that with TS segments, but moved to explicit init segments when MP4 support was added. The init segments are hundreds of bytes so they're not a huge deal but add up over the course of the entire stream.

In my opinion, there's not too much difference between init segments and I-frames. It's an explicit dependency between QUIC stream that introduces some head-of-line blocking. However the same head-of-line blocking is present if they are transferred over the same QUIC stream, or really any mode of transportation (ex. datagrams).

**Comment by suhasHere** [comment]
Thinking of it a bit more, typically in video calling the init information is sent as part of IDR frame and not separatly. Having then go together might be less error prone probably ?

**Comment by kixelated** [comment]
I'm in favor of a separate track per init segment, matching HLS/DASH. Either way this is no longer part of the transport draft.
