### ISSUE TITLE
Track Request Parameters

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#210]
https://moq-wg.github.io/moq-transport/draft-lcurley-moq-transport.html#name-track-request-parameters

First issue, it's in a weird section. The parameters mostly apply to 6.3 (all but one) but the section is in 6.6.1. 

<img width="298" alt="Screenshot 2023-06-08 at 8 26 37 PM" src="https://github.com/moq-wg/moq-transport/assets/432854/cc8de360-8a0a-4617-b6e4-629dd403f323">

Second issue, the types are not defined. GROUP SEQUENCE and OBJECT SEQUENCE are presumably varints, while AUTHORIZATION information is presumably a varint size followed by bytes? The encoding needs to be specified otherwise it's impossible to implement.

Third issue, and I hinted at it already, is that the parameters only apply to some messages and it's only mentioned at the very end. `This parameter is applicable in SUBSCRIBE REQUEST message`. The language is loose, and I'm not sure what I should do if I receive this parameter in an ANNOUNCE message.

**Comment by suhasHere** [comment]
on its placement,  +1, we should fix it.

On the params not applicable, we might want to add text to say, " ignore the parameters that are not expected or unknown" and this can be in general to all the parameters. This is very typical and allows extensibility and experimentation

**Comment by kixelated** [comment]
> On the params not applicable, we might want to add text to say, " ignore the parameters that are not expected or unknown" and this can be in general to all the parameters. This is very typical and allows extensibility and experimentation

I think we should have separate parameters for each message as the draft develops: SETUP Parameters, SUBSCRIBE Parameters, and ANNOUNCE Parameters. It made made sense to consolidate PUBLISH_INTENT and SUBSCRIBE_REQUEST together, but ANNOUNCE is quite different.

It's fine to copy-paste the only shared parameter (AUTHORIZATION INFO). It's just an opaque binary blob, and we might replace it anyway as part of leveraging existing authentication standards (something like #152).

**Comment by suhasHere** [comment]
yeah that seems fine change. At  some point we did stat that way and decided to move it to its own section and we can always move it later, if needed to

**Comment by kixelated** [comment]
Marked as `Implementation Blocker` because it's not specified how these parameters are encoded.

**Comment by martinduke** [comment]
> > On the params not applicable, we might want to add text to say, " ignore the parameters that are not expected or unknown" and this can be in general to all the parameters. This is very typical and allows extensibility and experimentation
> 
> I think we should have separate parameters for each message as the draft develops: SETUP Parameters, SUBSCRIBE Parameters, and ANNOUNCE Parameters. It made made sense to consolidate PUBLISH_INTENT and SUBSCRIBE_REQUEST together, but ANNOUNCE is quite different.
> 
> It's fine to copy-paste the only shared parameter (AUTHORIZATION INFO). It's just an opaque binary blob, and we might replace it anyway as part of leveraging existing authentication standards (something like #152).

The somewhat annoying bit about a per-message namespace is that we have tons of IANA registries. Editorially, I would be happy for each parameter/message instance but let's put it in the same namespace

**Comment by ianswett** [comment]
I believe this is fixed by #256

**Comment by martinduke** [comment]
If we converge on #256, yes this is fixed
