### ISSUE TITLE
SETUP message type

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#212]
There's a single SETUP message, but the contents change based on if the endpoint is a server or a client. [See the draft](https://moq-wg.github.io/moq-transport/draft-lcurley-moq-transport.html#name-setup).

This is difficult to implement in type safe languages. I would implement `ClientSetup` and `ServerSetup`, sharing the same ID. However, it's then difficult to implement a generic `decode` method as it needs to know the expected role to distinguish between the two.

I propose a separate `ClientSetup` and `ServerSetup` message akin to how TLS has a separate `ClientHello` and `ServerHello`. Alternatively, implement #138 to reclassify SETUP and OBJECT as control and data stream headers respectively.

**Comment by kixelated** [comment]
Hmm, so this isn't a problem in my code any longer since made SETUP a special message type. We should still figure out if both the client and server SETUP use the same ID, or separate IDs like TLS.

**Comment by fluffy** [comment]
I still like the idea of, if these message are different, they should have different names as it will just be confusing if they do not.

**Comment by ianswett** [comment]
Agreement these should be different message types, just like TLS.

**Comment by fluffy** [comment]
On call, agreed to set these as different messages

**Comment by kixelated** [comment]
Conveniently, message id=2 is currently not used. I propose ClientSetup = 1 and ServerSetup = 2.

**Comment by kixelated** [comment]
> Thinking about this a bit more, do we want to bake in the assumption that the client always speaks first into the protocol? For raw QUIC, typically, the server would have 1-RTT keys first.

I would love to see something like HTTP/3 SETTINGS where both endpoints can send the message in parallel. That requires version negotiation at a lower level in something like ALPN though.

The SERVER SETUP would be sent first in native QUIC while the CLIENT SETUP could be sent first with WebTransport (in parallel with CONNECT).
