### ISSUE TITLE
Draft version numbers

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#214]
It's time to specify some version numbers so we can attempt interop.

We should do something like QUIC, where draft versions are prefixed with 0xff (or something?).

**Comment by fluffy** [comment]
+1 The QUIC guys way over engineered this so I would be fine with just doing the same thing so we don't need to bike shed on it.

**Comment by kixelated** [comment]
Here's what I propose we copy:

https://datatracker.ietf.org/doc/html/draft-ietf-quic-transport-32#section-15-10

> Version numbers used to identify IETF drafts are created by adding the draft number to 0xff000000. For example, draft-ietf-quic-transport-13 would be identified as 0xff00000d.

We don't need semvar yet because each version WILL have breaking changes. I'd be totally fine with semvar for the final RFC, like one byte for the major/minor/revision. Although I also think negotiating extensions are more flexible.
