### ISSUE TITLE
Editorial notes

### ISSUE THREAD

**Issue by gwendalsimon** [moq-wg/moq-transport#218]
Here are some editorial notes on the document

- Line 72. “_MOQT is a generic protocol **is** designed to work_” 
- Line 91-93. “_The development of MOQT is driven by goals in a number of areas - specifically latency, the robustness of QUIC, workflow efficiency and relay support._” This sentence is intriguing. What does the robustness of QUIC mean? Latency, workflow efficiency, relay support are not “areas” or maybe area should be defined. (side note on the missing Oxford comma in this sentence)
- The Section 1.1.1. Latency as a whole is very confusing. HTTP-based streaming is not designed for low latency mostly due to the essential request-response paradigm. Queuing on the path has a insignificant impact on the end-to-end latency for HAS. The “speed at which a protocol can detect queuing” is not related to the relatively high latency issues of HAS. Overall, I see a mix of unrelated subjects here, which makes the paragraph overall meaningless. I would recommend starting the paragraph with a topic sentence (which may be the last one of the current paragraph).
- Line 120. “_Applying QUIC to HAS …_” (and the following sentences) is not necessary. The reasons for which QUIC does not bring advantages to HAS are still debatable on many points. This QUIC-on-HAS remark could raise unnecessary questions although the beginning of Section 1.1.2 is clear and sufficient to convey the message.
- Line 125. “_Universal_” has a too broad sense. Do you mean “Unicity of protocol in the whole pipeline” (or something like this)?
- Line 127. “_Internet delivered media today has protocols optimized for ingest…_” I don’t understand this sentence.
- Line 127. Some examples of protocols could be good to support these claims. Note that WHIP is an attempt to unify the protocol.
- Line 146. “_to treat relays as first-class citizens of the protocol_” is an excellent marketing message but it does not mean anything in a technical norm. Furthermore, see my two reserves above. I’d claim that the current draft is not making relay first-class, on the contrary.
- Line 179. “_a join point_” joint?
- Line 231. “_The application is solely responsible for the content of the object payload._” What is the application? It is a bit confusing. It has not been defined.
- Line 269 .“_within a single MOQT scope, subscribing to the same full track name would result in the subscriber receiving the data for the same track._” I am not sure to understand this sentence. Is a single MOQT scope a scope with only one server or do you mean “within a MOQT scope”? the two “same” adjectives are confusing too.
- Line 273. It would be better to stick to “_servers_” or to “_connection URIs_” to refer to the elements of the scope.
- Line 339. “The `authority` portion MUST NOT contain a non-empty `host` portion.” Is it a double negation to say that the ‘authority’ MUST contain an empty ‘host’ portion? 
- Line 357. This sentence may require a MUST.
- Line 359. “_for exchanging …_” and following sentences are not related to session initialization. They are rather remarks that would be a fit with the draft Section 4.
- +1 to the TODO remarks on line 381. This should be in Section 4.
- Line 654. “_it allows the peers…_” The term “_peer_” is used 7 times. It is supposed to be an “_endpoint_” (as defined Line 173), unless peer and endpoint have different meaning (in which case peer must be defined)
- Line 693. “_A relay that reads from a stream and writes to stream in order will introduce head-of-line blocking._” I don’t understand this claim.

**Comment by ianswett** [comment]
Thanks for the feedback.  I'm going to mark this as Editorial, but there are a number of points here.  If you believe any of them are not editorial (ie: "Line 357. This sentence may require a MUST."), please split into a separate issue.

**Comment by martinduke** [comment]
@mzanaty Please go through these and fix any that still apply.
