### ISSUE TITLE
Term QUIC is used in when it may not actually be QUIC

### ISSUE THREAD

**Issue by ianswett** [moq-wg/moq-transport#223]
Though MOQT is optimized for QUIC, it technically can go over WebTransport over HTTP/1 or HTTP/2.

There are a number of cases when QUIC is used when it could be something else and in most cases, specifying QUIC is not critical to the design.  For example "Consumer: A QUIC endpoint receiving media over the network."

Also, the definitions in 1.2 frequently reference terms defined later in the list.

**Comment by kixelated** [comment]
Absolutely. Stream prioritization and congestion control is better with QUIC, and thus can support lower latencies, but MoQ over TCP should still work well enough.

**Comment by ianswett** [comment]
I completely agree. This is an editorial point that there are times when 'QUIC' is used when it may not actually be QUIC.  In many cases, just removing that word makes the sentence both slightly more accurate and shorter.
