### ISSUE TITLE
Clarify conflicting announces across Producers

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#225]
While implementing MOQT relay,  I stumbled upon #204. Thinking through authorization implementation a bit more , I think the current spec needs to clarify this behavior.

Proposal is to say, when a conflicting announce happens,  the Relay MUST reject with an appropriate error type in the ANNOUNCE_ERROR message when the authorization disallows

```
ERROR_CONFLICT_TRACK
```

However, if the authorization policy allows such an allocation of namespaces, then clarify Relay interaction to indicate the most recent ANNOUNCE wins.

**Comment by afrind** [comment]
I'm unclear how this issue is different from #227 - can we merge them or clarify how they are different?

**Comment by suhasHere** [comment]
It can be treated same, if the solution applies to 2 different producers and same producers announcing more than once has the same behavior rules on the relay. 

@afrind do you think we would be fine with that ?

**Comment by afrind** [comment]
Ah, I see.

So this issue is specific to two different producers announce the same namespace (eg: different auth fields in ANNOUNCE), and 227 is the generic case (two ANNOUNCE messages with the same namespace, regardless of auth)?

I'll defer to you and @ianswett if it makes sense to keep separate or merge the discussion.

**Comment by suhasHere** [comment]
After considering few more use-cases, for cases where we need to support make before break, it would be good to have multiple announces be allowed. 

So here is the updated proposal

Proposal is to say, when a conflicting announce happens, the Relay MUST reject with an appropriate error type in the ANNOUNCE_ERROR message when the authorization disallows

``` ERROR_CONFLICT_TRACK ```

However, if the authorization policy allows such an allocation of namespaces, then clarify Relay interaction to indicate that multiple announces for the same namespace is allowed.

**Comment by afrind** [comment]
Individual Comment:

Bikeshed: ERROR_CONFLICT_TRACK -> ERROR_CONFLICTING_TRACK_NAMESPACE

Maybe simplify it to say, 

If a server receives multiple Announce's for the same namespace, it MAY send an Announce Error = ERROR_CONFLICTING_TRACK_NAMESPACE depending on authorization policy.

To clarify: if a server sends this error it doesn't support make-before-break?

**Comment by kixelated** [comment]
I'm borrowing HTTP status codes in my implementation, and yeah we need an equivalent of 409.

**Comment by ianswett** [comment]
Conclusion of the discsusion was to allow identical ANNOUNCEs and provide a varint or token to allow deciding which to prefer.

The case when the the data is not byte identical is a different issue, and there didn't seem to be interest in solving that at the transport layer.

**Comment by englishm** [comment]
+1 to some kind of unique token here. Unsure about the details.

**Comment by ianswett** [comment]
Closed by #525
