### ISSUE TITLE
Converge on terminology 

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#226]
Current terminology has caused lots of confusions on who does what in the MOQ end to end architecture.

https://datatracker.ietf.org/doc/html/draft-nandakumar-moq-arch-00 has an attempt to address the terminology in terms of Roles and the scope a given role brings into a a component in the architecture.

**Comment by ianswett** [comment]
If there is specific terminology that is causing problems, and I agree that there is, can you please file an issue for each and what the issue is?

For the future, I've created a Naming tag, opposed to the Architectural tag, since Naming does not affect the bytes on the wire or its functionality.

**Comment by suhasHere** [comment]
Label is fine to be Naming. thanks

Most common confusion points are

Publisher, Consumer, Endpoint, Producer, Subscriber,
Relay, Media Transformer, Special Relays

All of these are used to mean more than one thing in general

**Comment by afrind** [comment]
Dup of #157 ?
