### ISSUE TITLE
Announces with same name in reconnect

### ISSUE THREAD

**Issue by fluffy** [moq-wg/moq-transport#227]
When the relays received an ANNOUNCE with exact same name as previous ANNOUNCE, what happens? 

Options seem to be replace previous ANNOUNCE data or return an error. 

This is related to https://github.com/moq-wg/moq-transport/issues/225 and https://github.com/moq-wg/moq-transport/issues/204

Discussion to follow in thread

**Comment by fluffy** [comment]
One of use cases we should think about is a client that crashes and reconnects.

**Comment by afrind** [comment]
As an individual, 

The crash (or disconnect) use case is compelling for "the most recent one wins".  Are there applications where that policy would break something?

**Comment by fluffy** [comment]
I agree with Alan that "most recent" overwrites any earlier ones is best path forward.

**Comment by suhasHere** [comment]
+1 on most recent overwrites. this is what we do atleast today and it works fine to the amount we have tested.

**Comment by kixelated** [comment]
Going with the most recent ANNOUNCE works for me, so long as the relay MUST send an `ANNOUNCE_ERROR` and `UNSUBSCRIBE` for any matching subscriptions to the original session. Otherwise we'll introduce zombie announcements and subscriptions.

**Comment by fluffy** [comment]
WFM

**Comment by suhasHere** [comment]
> Going with the most recent `ANNOUNCE` works for me, so long as the relay MUST send an `ANNOUNCE_ERROR` and `UNSUBSCRIBE` for any matching subscriptions to the original session. Otherwise we'll introduce zombie announcements and subscriptions.

I Dont think existing subscriptions needs to be terminated. 

Let say the case where, A publisher disconnects due to getting into an elevator for a moment and sends announce on reconnect, sending out protocol messages to cancel the subscriptions on the second announce is too noisy.

**Comment by afrind** [comment]
As an individual: 

I don't think we need to force unsubscribe everyone if the relay successfully resubscribes to the new ANNOUNCE.

**Comment by kixelated** [comment]
> As an individual:
> 
> I don't think we need to force unsubscribe everyone if the relay successfully resubscribes to the new ANNOUNCE.
> 
> I think Luke is suggesting that the relay unsubscribe on the session that issued the old ANNOUNCE?

Yeah exactly. The upstream subscription is reissued to the new connection, but any downstream subscriptions can be maintained by updating a lookup table. I can elaborate what I mean if this isn't clear.

**Comment by ianswett** [comment]
Closed by #525
