### ISSUE TITLE
How should a relay route ANNOUNCE messages?

### ISSUE THREAD

**Issue by afrind** [moq-wg/moq-transport#228]
ANNOUNCE tells a relay where to route SUBSCRIBE messages for a given namespace.  Should there be a different message that serves the same purpose for ANNOUNCE?

Context: 

In my fledgling [moq-chat](https://afrind.github.io/draft-frindell-moq-chat/draft-frindell-moq-chat.html) protocol, there is a server entity that maintains a catalog of all the participants/tracks in the chat.  In order to perform auth, and keep the catalog up to date, I rely on the server seeing the ANNOUNCE message when a participant tries to join the chat.  However, if the clients and server are connected by a relay, it's unclear how the relay would know to forward the ANNOUNCE from a new client to the server.

Option 1:

This is "business logic", which is out of scope.

Option 2:

Add another message that an endpoint can send to indicate it would like to receive ANNOUNCE messages matching a given namespace.  This would be an optional message, and could co-exist with option 1.

Option 3 (I don't like this, including for completeness): 

Send it to every endpoint connected to the relay, and see if anyone gives ANNOUNCE OK.

**Comment by suhasHere** [comment]
It seems like it would be "Option 1"

**Comment by afrind** [comment]
Victor offered the idea that the moq-chat server could authorize users to join the chat when they subscribe to the chat catalog, rather than requiring the relay to forward participant ANNOUCE's to the server.  It's a little strange, in that the client will ANNOUNCE it's track namespace to the relay, and also has to communicate it to the server in the SUBSCRIBE_REQEUST's auth field, but ultimately workable. 

I think that solves my immediate need, though I'm not sure that solution and "business logic" will cover all use cases.

**Comment by suhasHere** [comment]
FWIW, in one of my deployment/implementations, the relay extracts the authz token and use it to validates the user. In a slightly different scenario, the relay has all the needed info as part of the token for it to make the decision locally too. 

That's the main reason I feel the transport cannot mandate how the business logic is setup other than provide recommendations, which we don't think should be in the core transport draft. May be arch draft can be updated to add some details in the next rev.

**Comment by kixelated** [comment]
Like I [mentioned here](https://github.com/moq-wg/moq-transport/issues/204#issuecomment-1653999951), there's actually two distinct ANNOUNCE messages. How they should be forwarded varies:

- `PLS_SUBSCRIBE` depends on business logic. If you're a 1:1 proxy, then forward it downstream (basically push). If you're a 1:N relay, then you might not want to push it to all downstreams, so you terminate and wait for a `SUBSCRIBE`.
- `PLS_ROUTE` on the other hand would be replicated to all downstreams (present and future). It's effectively a gossip protocol and a mechanism to indicate the origin for a broadcast.

**Comment by suhasHere** [comment]
If a relay will replicate to other nodes or not is very much relay and deployment decision.

On the same lines, how relays plays role in the authorization is also very much deployment specific.


I think what we have today meets the fine line to help subscribers meet the publishers without defining too much on how relays manage the internals.

**Comment by fluffy** [comment]
I think it should be out of scope of the MoQ spec on how the internals of the relays work. I view how relays route ANNOUNCE to other relays as part of those internal. The only thing we should spec about the behaviour of the relays is the black box behavior the clients needs to count on.

**Comment by afrind** [comment]
As an individual: 

I agree with everything you said there @fluffy.  I'm just not sure if "routing ANNOUNCE to a *client*" (as opposed to another relay) is also out of scope.

I like the way Suhas put it:

> I think what we have today meets the fine line to help subscribers meet the publishers without defining too much on how relays manage the internals.

I intended Option 2 in the issue description to be in-line with "helping subscribers meet the publishers" rather than being prescriptive about how a relay routes messages internally or performs auth.

> PLS_ROUTE

I haven't heard anyone state that they want something that looks like a gossip protocol.  If someone has a use case for it, maybe they can put it forward.  Otherwise, perhaps we can move forward with an assumption that is outside the design space for now.

**Comment by kixelated** [comment]
> > PLS_ROUTE
> 
> I haven't heard anyone state that they want something that looks like a gossip protocol. If someone has a use case for it, maybe they can put it forward. Otherwise, perhaps we can move forward with an assumption that is outside the design space for now.

I might be jumping to conclusions, but advocating for prefix matching in #204 implies the `PLS_ROUTE` behavior is desired.

Anyway, I agree with @fluffy. If an endpoint sends an ANNOUNCE, then all that means it that it will accept the corresponding SUBSCRIBE. There's no requirement that a relay forwards an ANNOUNCE provided it maintains this contract somehow (ex. inserts into a database).

**Comment by VMatrix1900** [comment]
> I haven't heard anyone state that they want something that looks like a gossip protocol. If someone has a use case for it, maybe they can put it forward. Otherwise, perhaps we can move forward with an assumption that is outside the design space for now.

I agree how the ANNOUNCE message is routed inside a relay service provider is internal. But if there are multiple relay service providers involved, ANNOUNCE routing would be useful for relay service provider chaining. In other words, IGP for ANNOUNCE does not need to be standardized, but BGP should.

**Comment by afrind** [comment]
I made a different proposal for how to accomplish chat functionality in "pure moq" without relying on routing announce.  See https://github.com/afrind/draft-frindell-moq-chat/pull/1.

It involves creating a "control track namespace".  The participants in the chat join and leave by sending an empty subscribe to a random, unique track name in control track namespace, with commands encoded in Track Request Parameters.  Love it? 
 Hate it?  

Happy to take the discussion over moq-chat repo, but since no one else wants ANNOUNCE to go more than one hop in moqt, I'll close this.
