### ISSUE TITLE
Resetting control streams

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#230]
There's an assumption in the current draft that some messages are partially reliable (OBJECT messages) while some are fully reliable (everything else, aka control messages). The ability to drop a message depend on the ability to reset the QUIC stream.

However, reseting a stream containing control messages wrecks havok on the subscription state machine. There's no way within QUIC determine if a messages was received or processed prior to a reset. For example, if I send a SUBSCRIBE on stream and then a receive a STOP_SENDING for that stream, then the subscription enters a limbo state:

1. The SUBSCRIBE was processed and a SUBSCRIBE_OK or SUBSCRIBE_ERROR is forthcoming.
2. The SUBSCRIBE was never processed and a SUBSCRIBE_OK or SUBSCRIBE_ERROR will never be received.

The only option currently is to set a timer after a reset is received. After a few RTTs or so, we assume the SUBSCRIBE was lost and issue a new SUBSCRIBE on a new stream, introducing latency in the process. Though things get extra weird if we receive a response after this timeout expires...

---

I think we either need to state:
1. Control streams MUST NOT be reset (like HTTP/3)
2. Reseting a control stream also resets all prior messages (ie. all prior SUBSCRIBEs).
3. Reseting a control stream resets all unacknowledged messages (ie. SUBSCRIBEs without SUBSCRIBE_OK).

Option 3 is problematic, since the subscriber knows that the OK was received prior to the reset but the publisher doesn't. Personally, I think option 1 is the best is there's a single control stream, while option 2 is the best if there's multiple (scoped) control streams. 

---

Regardless of the approach, data messages and control messages should be split (#31) because they have different reliability. A receiver should know if it can issue STOP_SENDING for an OBJECT without impacting control messages, especially if we take approach 1.

My application uses a bidirectional stream for control messages and unidirectional streams for data messages. It makes it very easy for the application to know if a stream is resettable just based on the ID.

**Comment by suhasHere** [comment]
From #96 , (s/channels/streams)
-- snip
Control and Data Channels
When a endpoint client or relay begins a transaction for media delivery, a new bilateral QUIC Stream is opened. This stream will act as the "Control Channel" for the exchange of data, carrying a series of control messages in both directions. There is one "Control Channel" setup per track. Control Channels are "one way" and are setup hop-by-hop between the participating MoQ entities. If a peer both sends and receive media, there will be different control channels for sending and receiving.

For exchanging media, OBJECT messages ({{message-object}}) belonging to a group are delivered over one or more unidirectional streams, called data channels, based on application's preferred mapping of the OBJECT and its group to underlying QUIC Stream(s).

The control channel will remain open as long as the peers are still sending or receiving the media. If either peer closes the control stream, the other peer will close its end of the stream and discard the state associated with the media transfer. The latter resulting in termination or clean up of stream states associated with the data channels.

-- snip


The meta level thinking there was ,  OBJECT messages sent over data streams  doesn't impact control stream. However closing a control stream, say for a track namespace, will end up closing all the data streams corresponding to the media transfer for the associated track namespace

**Comment by ianswett** [comment]
Resetting the control stream should be an error, given there is only a single control stream.
