### ISSUE TITLE
ANNOUNCE and SUBSCRIBE relationship

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#231]
I'm running into a bit of a conundrum with my implementation. ANNOUNCE and SUBSCRIBE contain a track namespace, but it's not clear how or if they are related.

Currently, ANNOUNCE is an optional message. It's meant to facilitate situations where publisher and consumer do not exchange the track namespace or authentication out-of-band. This was primarily for contribution, so a client could connect to a random edge and announce itself as an origin, but technically it also works for distribution. Let's assume one of those situations and ignore any pre-negotiation.

By receiving an ANNOUNCE, it implicitly becomes valid to issue a SUBSCRIBE to the given namespace. The message effectively carves out a space within the string namespace where a subscription might be served. Note that this is not a contract and the corresponding SUBSCRIBE could still fail, especially when the track name is invalid.

---

What happens after a subscriber receives a corresponding UNANNOUNCE (not specified)? Should the subscriber pretend like the original ANNOUNCE was never received? Does this mean:

1. Terminate any active subscriptions? 
2. No longer issue any new subscriptions?
3. Do nothing?
4. Undefined?

---

Likewise what if the subscriber rejects an ANNOUNCE with ANNOUNCE_ERROR? Should the publisher continue to serve subscriptions from this namespace? Does this mean:

1. Terminate any active subscriptions?
2. Prevent any new subscriptions?
3. Do nothing?
4. Undefined?

**Comment by kixelated** [comment]
In my opinion, the answer is 1&2 for both, but that seems extremely counter-intuitive based on how the draft is currently written, as there is no explicit relationship between ANNOUNCE and SUBSCRIBE.

However, when you step through how an application should behave in different roles, I think it becomes clear that some behavior needs to be standardized:

---

When a broadcaster receives ANNOUNCE_ERROR, it means the server rejected the broadcast. The client should terminate the broadcast and show an error message to the user.

Doing nothing (option 3) or leaving it undefined (option 4) are the worst option as a result as the broadcast will hang. The broadcaster needs an explicit signal that things are broken.

Does the broadcaster clean up any existing subscriptions, or wait for them to drain? This can happen if an ANNOUNCE_OK was followed by a later ANNOUNCE_ERROR, indicating the broadcast is no longer valid.

I think you sever, otherwise you're in this split-brain state where the ANNOUNCE is invalid but subscriptions are still valid for an arbitrary amount of time. This would block announcing a new broadcast until they have drained, and depending on the remote to cleanup just seems like a hang waiting to happen.

---

What happens when a relay receives an ANNOUNCE_ERROR or UNANNOUNCE? Well it probably occurred because the broadcaster disconnected and there's no longer route to the origin. Note that receiving an ANNOUNCE from the new origin would pre-empt this. 

Again, doing nothing is probably the worst option as traffic will be routed to dead origin. Leaving it undefined seems like a terrible idea as relays will diverge in behavior.

But does the relay sever any existing subscriptions, or just avoid issuing new ones? I think it should sever the subscriptions, explicitly telling downstream hosts that no more data is forthcoming. Otherwise, subscriptions will starve and features like ABR will randomly break, as they rely on new subscriptions.

---

And what happens when a viewer sends an ANNOUNCE_ERROR, which means the client rejected the broadcast. This use-case needs to be fleshed out, but it could be because a participant is unauthenticated, an incompatible catalog was advertised, or some fatal error occurred. 

What if the server performs prefetching (subscribing in anticipation of the client), should it sever those subscriptions?
Again, doing nothing or leaving it undefined will cause resources to be wasted. The ANNOUNCE_ERROR should be an explicit signal that the client has no intention of subscribing.

---

I think this points to a very clear relationship between ANNOUNCE and SUBSCRIBE. If the ANNOUNCE is terminated, then so are the corresponding SUBSCRIBEs.

* Is it valid to SUBSCRIBE after sending an ANNOUNCE_ERROR?
* Is it valid to SUBSCRIBE after receiving an UNANNOUNCE?
* Is it valid to SUBSCRIBE without receiving an ANNOUNCE?

I think the answer to all of them is "no". There are race conditions involved, but the endpoint should assume that all subscriptions are likely to fail.

However, we should still avoid introducing a round trip. You should be able to exchange the ANNOUNCE information out-of-band between coordinated endpoints, acting like an implicit (and irrevocable) ANNOUNCE message.

**Comment by kixelated** [comment]
> I think we might first want to clarify the semantics of sending and receiving ANNOUNCE_ERROR and SUBSCRIBE_ERROR _after_ receiving an ANNOUNCE_OK or SUBSCRIBE_OK for the same track namespace/full track name. We may even want to disallow that and have separate messages to cancel or error an active announcement/subscription. I read the problem differently if the initial ANNOUNCE fails versus someone cancelling it after it was valid for some time.

That's fair. I think @suhasHere called it ANNOUNCE_CEASE.

ANNOUNCE = "You can subscribe"
ANNOUNCE_OK = "I might subscribe"
ANNOUNCE_ERROR = "I won't subscribe"
ANNOUNCE_CEASE = "I will no longer subscribe"

I think there's enough similarity between ANNOUNCE_ERROR and ANNOUNCE_CEASE that we don't need separate encodings though.

> I'm inclined to leave this decision up to the application, rather than being prescriptive. Is there an interop problem if, say, a sender leaves a subscription active after an ANNOUNCE_ERROR? The receiver can always UNSUBSCRIBE. Maybe there's a usecase for moving new subscriptions to another endpoint, but continuing existing ones?

I think we should draw up a state machine. Leaving it up to the application is going to be an absolute mess because of the sheer number of permutations. I think this issue mostly centers around if the ANNOUNCE and SUBSCRIBE state machines are intertwined or separate. Actually trying to draw up those state machines first would help.

**Comment by afrind** [comment]
Individual comment:

The QUIC decision to separate the send and receive stream state machines made them both simpler.  So I'm inclined to say the same here and keep the coupling very loose.  

ANNOUNCE hints to the subscriber where to route certain subscribes and that's it.  If the publisher wants to revoke that hint, and the subscriber already routed subscribes or wants to route new subscribes without an active announcement, fine.  The publisher can unsubscribe them and/or reject the new ones if it needs to.  It was never required in the first place, so even if there's no active announcement, a receiver may still try to send a subscribe.

**Comment by kixelated** [comment]
I'm going to close this issue because there's not a concrete problem. I just kind of rambled on and it's frankly embarrassing to reread the "issue".

But I think the ambiguity of ANNOUNCE is going to keep being an issue, especially when trying to code generic endpoints.
