### ISSUE TITLE
Decide how to achieve ALPN-style functionality in WebTransport

### ISSUE THREAD

**Issue by ianswett** [moq-wg/moq-transport#233]
QUIC uses TLS that provides ALPN.  WebTransport does not currently have identical functionality.

@vasilvv to bring this up with the W3C as to what the right way forward is.

**Comment by vasilvv** [comment]
File w3c/webtransport#536

**Comment by afrind** [comment]
@vasilvv : can this be closed now?

**Comment by vasilvv** [comment]
Yes, this got solved in WebTransport.
