### ISSUE TITLE
Termination

### ISSUE THREAD

**Issue by kpugin** [moq-wg/moq-transport#24]
> The QUIC connection can be terminated at any point with an error code.

Hm... this will prevent multiplexing, which I think would be pretty important on delivery side

**Comment by afrind** [comment]
Yeah this is an excellent point.  I assume we want to support more than one different video on the same QUIC connection?  Do we do that with different WebTransport sessions per video, or is there a video grouping within the WT session.  If it's the latter, there needs to be a way to terminate only one of the videos but not all of them.

**Comment by kixelated** [comment]
WebTransport technically has the ability to pool multiple sessions over a single QUIC connection, although I'm not sure that will get much traction.

What about an explicit TRACK_END frame like RUSH? We could still send CONNECTION_CLOSE for fatal errors.

**Comment by kpugin** [comment]
I know that for our use-cases, while ingestion may not need to be multiplex, for distribution - it pretty much must have.
So I think we should avoid touching QUIC connection - terminating it should be responsibility of QUIC endpoints, for MOQ we should have a way to terminate MOQ "session" whatever that is, in pull world - that would be "moq request", for PUSH - we going to need to identify that "push" session

**Comment by suhasHere** [comment]
+1 to having multiplexing. We can have per stream way to finish or terminate and need a way to identify that as part of MoQ WebTransport Session
