### ISSUE TITLE
ANNOUNCE_OK has no Namespace length

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#240]
In principle, the receiver could do some sort of longest-match or something, but this will be really painful if, for example, one namespace is a substring of another.

**Comment by martinduke** [comment]
Oh, it's implied by the message length. D'oh.

**Comment by kixelated** [comment]
I don't like how it's implied by the message length tho. It means an encoder/decoder needs two string types, one with an explicit prefix and one with an implicit length.

**Comment by martinduke** [comment]
I can deal with that, but feel free to reopen this if you are dissatisfied.
