### ISSUE TITLE
server-sent ROLE parameters

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#250]
Sec 6.1.1.1 specifies client sending or ROLE, and says nothing of server-sent.

I guess server-sent ROLE is not needed, but maybe we should fail if it is sent?

**Comment by kixelated** [comment]
I filed #151 about the role parameter. The client doesn't actually know what the server intends to do. The server should be able to reply with its functionality, which might be a subset of what the client can support.
