### ISSUE TITLE
What's the point of mandatory SETUP parameters?

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#251]
Parameters are a useful tool for optional fields in a message.

But AFAICT, none of the SETUP parameters are actually optional. Clients MUST send ROLE.  #151 and #250 discuss the server ROLE situation, but ISTM the server ROLE will be either required or forbidden.

Meanwhile, PATH will be required for raw QUIC clients and forbidden for all other cases.

So why not make these part of the SETUP message and save ourselves all the parameter encoding overhead? It's true that it would require different formats for Webtrans client, Raw QUIC client, and server, but we've already split SETUP into client and server variants.

I would not be opposed to leaving parameters in SETUP with an empty registry, as it would be a good extension point for capability negotiation.

**Comment by kixelated** [comment]
Yeah, it's quite frustrating right now. Especially the server SETUP, because it supports generic parameters but receipt of any registered kinds should be an error.

However the messages do need to be generic so they can be used to perform version negotiation. I wish we could punt version negotiation to another layer like ALPN but no equivalent exists in WebTransport.

**Comment by martinduke** [comment]
Hmm, interesting point about VN. I did a PR, so the group can decide.

**Comment by vasilvv** [comment]
> So why not make these part of the SETUP message and save ourselves all the parameter encoding overhead?

TLS used to do that, and as a result, like half of TLS client hello in 1.3 are unused legacy fields with fixed values.  Though I guess if we defer version negotiation to ALPN, this is less of an issue.

**Comment by martinduke** [comment]
It might be worthwhile to sketch out exactly what VN looks like. Is the idea here that the client will include parameters for every version for which it advertises support? Adn then the server responds with the subset of parameters for the chosen version?

**Comment by martinduke** [comment]
People who know me from QUIC will know that I am not a fan of negotiation via ALPN.

**Comment by ianswett** [comment]
We now have some text on negotiation.  I think if we saw a PR for this, it could be landed, especially now that SETUP has been split into two in #297

**Comment by martinduke** [comment]
The VN text answers the question of what SETUP parameters are for. Closing.
