### ISSUE TITLE
Can you have subscribe error after OK 

### ISSUE THREAD

**Issue by fluffy** [moq-wg/moq-transport#261]

**Comment by fluffy** [comment]
one question is if they come on different streams can they get out order

**Comment by suhasHere** [comment]
My inclination is to send a SubscriptionEnd {} message with appropriate Reason Code set. This will help to support the case that we discussed on publisher wanting to indicate wanting to stop publishing

**Comment by ianswett** [comment]
SUBSCRIPTION_END and SUBSCRIPTION_END_ERROR could be split for the graceful vs non-graceful cases.

**Comment by fluffy** [comment]
Discussion in room  seems to be rather not have an error after OK but instead use new messages or in subscribe_end message

**Comment by kixelated** [comment]
I'd like to consolidate messages at some point, but we can revisit later.
