### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#263]
Could we include an [.editorconfig](https://editorconfig.org/) file? It wouldn't be required, but it would reduce the amount of reformatting required.

[The QUIC configuration is good.](https://github.com/quicwg/base-drafts/blob/main/.editorconfig)

```ini
root = true

[*.md]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = true
max_line_length = 80
trim_trailing_whitespace = true
```

```
% editorconfig-checker draft-ietf-moq-transport.md
draft-ietf-moq-transport.md:
	6: Trailing whitespace
	11: Trailing whitespace
	175: Trailing whitespace
	693: Line too long (129 instead of 80)
	704: Line too long (149 instead of 80)
	705: Line too long (174 instead of 80)
	872: Line too long (140 instead of 80)
	953: Trailing whitespace
	954: Trailing whitespace
	955: Trailing whitespace
	1040: Trailing whitespace

11 errors found
```

Most of those long lines were added by me, since my IDE is configured to use 120 lines and tabs by default. If we check in the `.editorconfig` file then my IDE ([VSCode](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)) will use those settings instead.

**Comment by kixelated** [comment]
A markdown linter in general might be nice. I don't know what is typical for IETF documents.

**Comment by afrind** [comment]
Does the repo use the I-D template repo?  I find it has a lot of useful lint checks - you can't push commits that fail the lint

**Comment by kixelated** [comment]
> Does the repo use the I-D template repo? I find it has a lot of useful lint checks - you can't push commits that fail the lint

We should use the I-D template. This repo was my first IETF draft, so I didn't know about the template and made something custom.
