### ISSUE TITLE
Write up Version Negotiation/Extension Negotiation

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#265]
I suggested a mechanism in Cambridge and there was broad agreement. We should write it down.

**Comment by afrind** [comment]
It might help to put the high level summary here in the issue?

**Comment by martinduke** [comment]
- The client sends a list of supported versions and the union of all parameters required for SETUP messages in any of the supported versions.

- These parameters can include ones that communicate support for an extension.

- The server replies with the selected version, any parameters required for SETUP messages of that version, including any supported extensions as parameters.
