### ISSUE TITLE
Editorial: Error codes

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#266]
I'd like to structure/format the error codes like the QUIC draft. That means all error codes named with `ALL_CAPS` and the error codes inlined with the definition. See: [QUIC](https://datatracker.ietf.org/doc/html/rfc9000#section-20.1) vs [MoqT](https://moq-wg.github.io/moq-transport/draft-ietf-moq-transport.html#name-termination)

I can make the PR if it sounds gud.

**Comment by martinduke** [comment]
@kixelated has no interest in a PR, so closing.
