### ISSUE TITLE
"SUBSCRIBE OK" and "SUBSCRIBE ERROR" or SUBSCRIBE_OK and SUBSCRIBE_ERROR

### ISSUE THREAD

**Issue by ianswett** [moq-wg/moq-transport#275]
I'd make this change in a single PR, but I prefer frame names have underscores to having to quote them when referring to them when they are two words.

Observed when reviewing #274

**Comment by afrind** [comment]
Individual Preference: always underscore

**Comment by suhasHere** [comment]
+1 let's use underscore . Makes readability and editing so much better
