### ISSUE TITLE
Is GOAWAY bidirectional?

### ISSUE THREAD

**Issue by ianswett** [moq-wg/moq-transport#276]
PR #264 has GOAWAY as only sent from server to client, but there may be use cases for the reverse as pointed out by @afrind

**Comment by DanielFay22** [comment]
I'm not really clear, what would be the use case for client -> server GOAWAY? If the only use case is a client indicating end of subscription, then I think that would be better encoded in the SUBSCRIPTION_END that Alan mentioned, but if there's other use cases then I could see GOAWAY making more sense.

**Comment by ianswett** [comment]
What if the client is not the original source, but rather a relay.  In that case, the relay may need to restart/etc.  One option is the relay sends a GOAWAY and the client starts publishing to a new relay.  But does it need to do something about it's upstream subscriptions?

**Comment by fluffy** [comment]
FWIW ... relay to relay is out of scope - we are only doing client to relay - we would need a lot more to have a full relay to relay protocol

**Comment by kixelated** [comment]
A client-initiated GOAWAY is weird but kind of makes sense.

I'm thinking of the dual ingest case when there are two connections from broadcaster to relay(s). If the client sends a GOAWAY message, it's an explicit signal to the relay that it needs to UNSUBSCRIBE to everything and find another route to the content. The party isn't over, you just can't stay here.

But there's some overlap with UNANNOUNCE. I'm not sure if we need client-initiated GOAWAYs.

**Comment by fluffy** [comment]
That use case makes sense.   "The party isn't over, you just can't stay here."  is awesome tag line for use case. 

For a graceful shutdown of a publisher,  I think the way to do that would be the client publishing sends un-annouce and the relay then ends all the subscriptions, once all the subscriptions are gone, the client closes the connection.

**Comment by ianswett** [comment]
With UNANNOUNCE and ANNOUNCE_CANCEL (#392), I'm inclined to think we don't need this.

**Comment by afrind** [comment]
UNANNOUNCE tells the receiver not to send new SUBSCRIBEs, but doesn't currently mean "please UNSUBSCRIBE and find somewhere else to SUBSCRIBE if you still want content".  Do we want a message to convey that semantic?

**Comment by vasilvv** [comment]
It definitely feels odd given that outside of SETUP and ROLE parameter, MoQT is a symmetric protocol.

**Comment by ianswett** [comment]
My current thinking is that GOAWAY is useful for all publishers, even if they're 'clients' (ie: an original publisher).  It also seems useful if an original publisher is publishing to an ingestion server that is about to restart and the server wants to cause them to connect to a different ingestion server.

I don't have a clear use for the end subscriber sending a GOAWAY, but it also doesn't seem particularly harmful.
