### ISSUE TITLE
PADDING vs PING

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#30]
> Senders MAY periodically pad the connection with QUIC PING frames to fill the congestion window.

I didn't want to go into more detail, but PADDING frames can cause deadlocks due to the fact they are congestion controlled but do not elicit an acknowledgement. They also don't test the if the network could support the higher acknowledgement frequency potentially caused by a higher bitrate.

Should we remove this line, explain it in more detail, or leave as is?

**Comment by LPardue** [comment]
I found this line stuck out on my first reading.

If you need to fill a congestion window and need to elicit an ack, why not suggest many PADDING and one PING? Or if you don't want tocmake a concrete recommendation, explain the problems and provide non-exhaustive examples how somebody could avoid them.

**Comment by kixelated** [comment]
I believe many PADDING packets followed one PING packet would still still have issues if the PING packet is lost. It wouldn't fully deadlock, but it would rely on the PTO timer to eventually retransmit the PING packet, elliciting an acknowledgement, and freeing up the congestion window held by the PADDING packets.

You could interleave more frequent PING packets to reduce the chance of random loss causing a stall, but you might as well send only PING packets then.

**Comment by LPardue** [comment]
To put things another way, sending a packet that is MTU sized and filled with 1000+ PING frames sounds weird. In H2 there are DoS vectors related to PING frame processing. I know QUIC is different but this normative recommendation sticks out.

What is different if an endpoint sends several QUIC packets, each composed of many PADDING frames and a single PING frame?

To put things another way, sending a packet with

**Comment by kixelated** [comment]
Oh, my QUIC library just coalesces any consecutive PING frames as a single frame, likewise for PADDING. I suppose that's less obvious to implement.

How about changing the language to:
> Senders MAY pad the connection with congestion controlled, ack-eliciting packets to periodically become network-limited.

**Comment by kixelated** [comment]
It's more inclusive as well because another approach would be to speculatively retransmit STREAM frames, potentially adding PADDING if needed.

**Comment by LPardue** [comment]
This might be down to my reading of what "fill the congestion window" means. If it's read like "fill the pipe with bytes in flight" sending only one PING in a packet doesn't sound right?

I still might be off track here but it seems like we can avoid saying "MAY pad the connection  " - QUIC already let's endpoints do that and no point restating things defined elsewhere. So perhaps more like

> senders might find it beneficial to avoid becoming application limited. One strategy for doing this is by padding the connection with congestion-controlled, ack-eliciting packets.

**Comment by kixelated** [comment]
That sounds good to me. Plus "filling the congestion window" doesn't even make sense for paced CC algorithms.

**Comment by suhasHere** [comment]
I wonder if we need to go in detail on how the QUIC library does react is needed at all ? This is an implementation detail and can be just an informal note if needed

**Comment by martinduke** [comment]
I think it's worth it to mention the need for some sort of padding in the draft.

I would be comfortable with a recommendation of sending PING + PADDING packets.

**Comment by afrind** [comment]
This section got deleted in the most recent version.  @kixelated : should we close it out?  Open a new issue to track adding these kind of performance considerations back in?

**Comment by kixelated** [comment]
I don't think we need this text. It's more of a best practice and tied very closely to congestion control.

I think live media is difficult enough that we could have have an entire document surrounding congestion control mechanisms to minimize latency. Or we can leave it undefined and let implementors figure it out...
