### ISSUE TITLE
GROUP_SEQUENCE and OBJECT_SEQUENCE are overcome by events

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#300]
These parameters have been replaced with explicit fields in the SUBSCRIBE message.

All that's left (outside of SETUP) is AUTHORIZATION_INFO in SUBSCRIBE and ANNOUNCE.

I would just as soon get rid of non-setup parameters entirely and have an "auth_info_length" field in the messages which can be zero.

At a minimum, we need to eliminate GROUP_ and OBJECT_SEQUENCE.

**Comment by kixelated** [comment]
> I would just as soon get rid of non-setup parameters entirely and have an "auth_info_length" field in the messages which can be zero.

+1

I would go even further and make a dedicated AUTH message.
