### ISSUE TITLE
Consolidating SUBSCRIBE errors

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#310]
As mentioned in #309, there are 3 different ways for a publisher to close a subscriber, each with minor differences.

- `SUBSCRIBE_ERROR`: I never sent you an object.
- `SUBSCRIBE_FIN`: There are no more objects to send after group/object X/Y.
- `SUBSCRIBE_RESET`: There are more objects after group/object X/Y... but I won't send them.

A few things:

### 1. `SUBSCRIBE_ERROR` naming
I think it should be renamed since it's not the only ERROR message. Maybe `SUBSCRIBE_REJECT`?

### 2. `SUBSCRIBE_FIN` and `SUBSCRIBE_RESET` are virtually identical
The only difference is that one has an error code. Otherwise they both include a final group/object and it's up to the application/library to decide if they wait for the final object(s). I'd like to only implement this once but right now I have to copy/paste any code to handle these almost identical messages.

What if we merged them and use error code 0 to signal a FIN. The reason phrase should be removed as part of #273.

### 3. It's difficult to determine which messages are protocol violations

There really needs to be a state machine like #237 with this many ways to terminate a subscription.

I think these are all protocol violations:
- `SUBSCRIBE_OK` then `SUBSCRIBE_ERROR`
- `SUBSCRIBE_ERROR` then `SUBSCRIBE_*` 
- `SUBSCRIBE_RESET/FIN` then `SUBSCRIBE_*`

My interpretation of the draft is that a `SUBSCRIBE_FIN` followed by a `SUBSCRIBE_RESET` is invalid, which is not obvious and unlike QUIC.
> A subscription remains active until it expires, until the publisher of the track terminates the track with a SUBSCRIBE_FIN (see [Section 6.8](https://moq-wg.github.io/moq-transport/draft-ietf-moq-transport.html#message-subscribe-fin)) or a SUBSCRIBE_RST (see [Section 6.9](https://moq-wg.github.io/moq-transport/draft-ietf-moq-transport.html#message-subscribe-rst)).

### 4. Do these error distinctions actually matter to the transport?

I don't think so. The library/relay behavior doesn't change based on `SUBSCRIBE_RESET/FIN`. The only thing that miiiight differentiate between the two is the application, which can use errors codes for this purpose. At the very least I would merge these two messages.

But I would also like to explore a single way for the publisher to close a subscription. The application can signal the nuanced differences between errors (ex. error code 404 vs 410). The library/relay doesn't care, it just forwards the error code.

**Comment by afrind** [comment]
Individual Comment:

> The library/relay behavior doesn't change based on SUBSCRIBE_RESET/FIN.

The inspiration for FIN vs RST in moq came from HTTP caching.  If a resource has no content-length, and the caching proxy has received N bytes, does it have the entire resource, or does it need to refetch the tail?  If that response was terminated with a FIN (H2 or H3), then it has the whole resource.  If it was terminated by a RST, it can't assume that it does.

So the value I see in these two messages is for a moq relay is similar.  A client connected to the relay and subscribed to a track, which fowarded the subscribe to a publisher.  The track was published to the relay and ended with a FIN.  Another client subscribes to this track from the beginning (Absolute/0,0) and no end.  Does the relay need to resubscribe upstream?

Now suppose that the connection from the publisher to the relay closed abruptly, or the track was terminated with SUBSCRIBE_RST.  This is a signal to the relay that it's worth another subscribe to find out where the end of the track is.

I can live if we consolidate the framing to a single message, and define a special error code to mean FIN, but I do think the transport needs to see the difference.
