### ISSUE TITLE
Clarify how to end a SUBSCRIBE at group N

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#312]
If I wanted to receive all objects in group N, I would issue:

```
SUBSCRIBE
end_group=absolute/N
end_object=none
```

However the draft sneaks this restriction in, and it would actually be a protocol violation:

> EndObject's Mode MUST NOT be None if EndGroup's Mode is not None.

It wasn't clear to me until chatting with Alan how you're supposed to do it:

```
SUBSCRIBE
end_group=absolute/N+1
end_object=absolute/0
```

It's clarified in example 5, but I don't think this is obvious and it feels like an off-by-one. For example, if N was the last group in the broadcast, I can imagine some implementations incorrectly throwing an error or somehow mishandling it.

**Comment by afrind** [comment]
Individual Comment:

> the draft sneaks this restriction in

This was discussed on the PR here: https://github.com/moq-wg/moq-transport/pull/289#discussion_r1368916351.

Given how subscribe locations work (end is exclusive), end=N+1/0 means "including through the end of group N".  The question is whether we should have more than one way to do things, and defaults when values are not present.

**Comment by kixelated** [comment]
> Individual Comment:
> 
> > the draft sneaks this restriction in
> 
> This was discussed on the PR here: [#289 (comment)](https://github.com/moq-wg/moq-transport/pull/289#discussion_r1368916351).

Sorry, bad choice of word there. I meant that it's not immediately obvious why the restriction exists, and what it impacts.
