### ISSUE TITLE
SUBSCRIBE_RST/FIN with null final Group/Object

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#313]
`SUBSCRIBE_RST` and `SUBSCRIBE_FIN` define:

> Final Group: The largest Group Sequence sent by the publisher in an OBJECT message in this track.
> Final Object: The largest Object Sequence sent by the publisher in an OBJECT message in the Final Group for this track.

However, what happens if no objects were ever produced/sent?

**Comment by afrind** [comment]
Individual Comment:

Oops.  Two possible ways to handle this:

1) Flag indicating presence of these fields (Use Location now that is defined elsewhere?)
2) Change the semantics of the fields to be exclusive (eg: it is the first object NOT sent), so 0/0 means none.

**Comment by ianswett** [comment]
I'm inclined towards 0/0, because optional fields are more complex to parse and I would expect the existing logic to work correctly with 0/0.

**Comment by kixelated** [comment]
Let's say the last object delivered by the relay is `group=5 object=29`. Does the relay send RESET `group=5 object=30` or `RESET group=6 object=0`? Is the subscriber able to infer the presence of future objects? What if either of those objects actually exist in the cache?

**Comment by afrind** [comment]
Individual Comment:

If we use exclusive encoding then I'd say that the receiver shouldn't infer the existence of non-existence of the named object, and either 5/30 or 6/0 works, but 5/30 is preferable?

**Comment by fluffy** [comment]
If you define there will be no objects greater than or equal to these, then 0/0 makes total sense.  So 0/0 for null case and say the last group ID of the last object publish was 10 then the value in SUB_FIN would be 11.

**Comment by ianswett** [comment]
In #343 we went with an explicit flag, so I'm inclined to do the same here for consistency.
