### ISSUE TITLE
VarInt parameters length mismatch

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#314]
Currently, VarInts have two lengths:

1. In the parameter length.
2. In the first two bits of the parameter value.

The decision in #294 was that the two MUST match, which is a good solution without a full #256 reform.

However:

> If the parameter value is a varint, but the self-encoded length of that varint does not match the Parameter Length field, the receiver MUST ignore the parameter using the value in the Parameter Length field.

Ignoring seems like the wrong play. For example, we know the role parameter (0x0) is a VarInt in the current draft. However this text says I MUST ignore any errors when parsing this varint and pretend like the parameter was never sent, which is both unenforceable and a major foot-gun (silently ignoring parameters).

I think we close the connection with an error if there's an error parsing a known parameter.

**Comment by martinduke** [comment]
If a parameter is unknown, then the parser doesn't know if the value is a varint and therefore can't check the length match.

I thought it was better to have consistent behavior than not, because it's easier to write and easier to reason about. But if this has actual downstream consequences, I could be convinced otherwise.

**Comment by kixelated** [comment]
I don't know what I was smoking when I came up with this title. My concern is that when a **known** parameter has the wrong length, the text says the decoder MUST ignore it. I think we should error; u messed up.

**Comment by martinduke** [comment]
I understand what you mean. My point was that an unknown parameter has an inevitable result, and trying to make the processing for known parameters the same had some advantages.

We'll discuss today.

**Comment by ianswett** [comment]
Conclusion was to make it an error instead of skipping over the field if there's a length mismatch.
