### ISSUE TITLE
Impossible to know group FIN

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#318]
The current approach of allowing any OBJECTs to arrive on any stream makes it impossible for the receiver to know when a group ends.

There's a few conditions when you need to know the end of a group:

1. A relay being told to terminate the subscription after group N (subscription hints).
2. A relay knowing when to close a QUIC stream (if it writes a group per stream).
3. A decoder deciding when to start decoding/rendering the next group (ex. GoP).

Likewise there's a similar problem of knowing when there's an gap within a group. There's no way to signal that OBJECT X will never arrive, so the receiver should not wait for it.

**Comment by kixelated** [comment]
I strongly advocate a 1:1 mapping for group to stream. Objects within a group are in order, but there may be gaps. Gaps can be detected via sequence numbers and the end is detected via stream FIN.

**Comment by kixelated** [comment]
Alternatively, we could have `OBJECT_DROP`, `GROUP_DROP` and `GROUP_FIN` control messages. I think this is a mess, and the receiver would need a corresponding `STOP_GROUP` in response to an unrecoverable gap caused by `OBJECT_DROP`. 

I don't think we can annotate OBJECTs with a FIN flag because they're lossy. You need some reliable mechanism to signal the end.

**Comment by kixelated** [comment]
Maybe this a duplicate of #315 ?

**Comment by afrind** [comment]
The issue mentioning Last Object Previous Group is in #224

**Comment by fluffy** [comment]
I think the best solutions to this is a header on the last object in the group that indicates it is the last object in the group.

**Comment by afrind** [comment]
Individual Comment:

> I think the best solutions to this is a header on the last object in the group that indicates it is the last object in the group.

I share Luke's concern above about OBJECT being somewhat unreliable.  I think a GROUP_FIN message with stronger reliability guarantees would look similar on the wire but work better.

eg:

Instead of 

```
OBJECT(G1,O1)  OBJECT(G1,O2)  OBJECT(G1,O3,last)
```

Have


```
OBJECT(G1,O1)  OBJECT(G1,O2)  OBJECT(G1,O3), GROUP_FIN(G1, O3)
```

This works better than implicit mapping from groups to streams.  A relay might need to close a connection with an open stream, but wouldn't want to reset it and wouldn't want the stream FIN to be interpreted as a group FIN.  I don't want to put GROUP_FIN on the control stream, but that would be the safest.

I think the other messages Luke mentioned related to DROP are probably an orthogonal issue.

**Comment by kixelated** [comment]
> I think the other messages Luke mentioned related to DROP are probably an orthogonal issue.

Agreed, I'm just bringing it up early because stream mapping has massive ramifications on what control messages we'll need in the future.

**Comment by fluffy** [comment]
you guys have convinced me

**Comment by huitema** [comment]
As I mentioned during the interim meeting, it makes sense to put that information in the header of the next group. Something like:
~~~
STREAM_HEADER_GROUP Message {
  Subscribe ID (i),
  Track Alias (i),
  Group ID (i),
  Previous Group ID(i),
  Last Object ID of Previous Group(i),
  Object Send Order (i)
}
~~~
That information can be used by the receiver to decide when to start playing the new group, and when to wait for more information instead. It is useful:

* when using "stream per object", to understand how many individual objects are expected for the previous group,
* when using "stream per group", if group numbers are skipped.

The downside is that the relay needs to know the value of previous group and last object before sending the first object of the next group. This may or may not be a problem in practice -- relays may be receiving the information from the origin. If the relay sets an overoptimistic value of previous object, it will have to send some kind of replacement for the skipped objects, such as
~~~
STREAM_HEADER_RESET_GROUP
{
  Group ID (i),
  Reset At Object ID (i)
}
~~~
Which will inform the receiver that the specified object ID and the following ones will not be sent for this group.
