### ISSUE TITLE
Subscriber rejecting ANNOUNCE

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#319]
> Relays respond with an ANNOUNCE_OK or ANNOUNCE_ERROR control message providing the result of announcement. The entity receiving the ANNOUNCE MUST send only a single response to a given ANNOUNCE of either ANNOUNCE_OK or ANNOUNCE_ERROR.

The problem is not possible for the subscriber to reject an ANNOUNCE afterwards. This would be very useful, for example to inform a publisher that no more subscriptions will be routed to them for whatever reason. Examples:

1. The auth parameter in ANNOUNCE has expired.
2. Another publisher has sent an overriding ANNOUNCE (reconnect?)
3. The broadcast has been closed remotely, ex. some moderation tool.

Without this message, the only recourse for the subscriber is to close the connection. This won't work if multiple ANNOUNCE messages are pooled over the same connection, nor is it clean.

**Comment by kixelated** [comment]
I propose two options:

1. `ANNOUNCE_RESET` can be sent after `ANNOUNCE_OK`.
2.  We add `ANNOUNCE_RST` and `ANNOUNCE_FIN` to mirror `SUBSCRIBE`.

I personally hate 3 separate messages for a subscriber to close an announce, or a publisher to close a subscription. See #310

**Comment by fluffy** [comment]
very trivial bikeshed comment ...  I would prefer to call it something other RESET ( and also other places we use RESET ). I get the TCP analogy but I think that is the wrong way to think about this. I would prefer something like REVOKE.

**Comment by ianswett** [comment]
Conclusion is that we do need to add a new frame to end an ANNOUNCE.

Additionally, there was a principle stated that we should not rely on closing the session as the typical or optimal way to close state and close either an ANNOUNCE or SUBSCRIBE.

**Comment by ianswett** [comment]
On the call today, people tend to prefer ANNOUNCE_CLOSE over ANNOUNCE_CANCEL as a name.  They also prefer merging SUBSCRIBE_RESET and SUBSCRIBE_FIN into a single message, possibly SUBSCRIBE_CLOSE.

**Comment by ianswett** [comment]
On an editorial note, it'd be nice to have subsections for publisher/subscriber to make it clearer to the reader.
