### ISSUE TITLE
GOAWAY seems overly restrictive

### ISSUE THREAD

**Issue by LPardue** [moq-wg/moq-transport#32]
The general motivation here isn't bad but mandating client behaviours in response to these types of messages seems a bit like overreach. The requirements also more restrictive than H2 or H3 GOAWAY, which are on theory also available as a capability in the same connection. 

Rephrasing the text can probably hit the notes you want with respect to preserving service continuity, without painting people into corners.

**Comment by kixelated** [comment]
Sure, I agree.

**Comment by jordicenzano** [comment]
> The endpoint successfully drained the session after a GOAWAY was initiated (Section 6.9).

This seems confusing. Do you mean:  The server endpoint is asking the client to terminate the session and reconnect as soon as possible because it wants to drain / shutdown

**Comment by jordicenzano** [comment]
> SHOULD remain connected on both connections for a short period

I think this has bad implications from the client:
        - Needs to keep 2 connections (more complexity)
        - I will double the BW required for that connection during some period of time (that could be a big problem)

What about something like: The client will ensure to not create gaps (data loss) between connections for all the tracks, making sure the switch will be done at group boundaries for all tracks.
   - So if last object sent for track 1, group 1 is N (last in the group 1) for connection 1,
   - Then,  the 1st object sent in connection 2 for track 1, will be: group 2 object 0
 
Optionally, the client can keep 2 connections open and the server side should implement dedupe
