### ISSUE TITLE
SUBSCRIBE REQUEST parameters

### ISSUE THREAD

**Issue by rom1v** [moq-wg/moq-transport#321]
Hi,

I have just read the RFC, and I have a question about the `SUBSCRIBE REQUEST` description:

```
SUBSCRIBE REQUEST Message {
  Full Track Name Length (i),
  Full Track Name (...),
  StartGroup (Location),
  StartObject (Location),
  EndGroup (Location),
  EndObject (Location),
  Track Request Parameters (..) ...
}
```

> Track Request Parameters: The parameters are defined in [Section 6.1.1](https://datatracker.ietf.org/doc/html/draft-ietf-moq-transport-01#version-specific-params)

If I'm not mistaken, these Track Request Parameters are:
 - GROUP SEQUENCE Parameter
 - OBJECT SEQUENCE Parameter
 - AUTHORIZATION INFO Parameter

It seems to me that `StartGroup`/`EndGroup` and `StartObject`/`EndObject` overlap (i.e. are partially redundant) with `GROUP SEQUENCE` and `OBJECT SEQUENCE`, don't they?

What if `StartGroup` and `GROUP SEQUENCE` refer to different groups?

(I probably misunderstood something or miss context.)

Another small question:

> EndObject's Mode MUST NOT be None if EndGroup's Mode is not None.

IIUC, this means that it is not possible to subscribe for Groups 42 to 47 without specifying the last object number in group 47? (just a theoretical question)

Thank you for your time :slightly_smiling_face:

**Comment by martinduke** [comment]
Group Sequence and Object Sequence should have been deleted

**Comment by kixelated** [comment]
Yeah we forgot to delete them before releasing draft-01. See: #302 

As for `EndGroup`, I agree and filed #312. You're apparently supposed to EndGroup+1 and EndObject=0

**Comment by rom1v** [comment]
> Group Sequence and Object Sequence should have been deleted

Oh, ok, that makes more sense now :+1:

Thank you.
