### ISSUE TITLE
Proposal for a TRACK_STATUS and TRACK_STATUS_OK messages

### ISSUE THREAD

**Issue by wilaw** [moq-wg/moq-transport#332]
It is useful for a client to be able to discover attributes of track at a relay (publisher)

- is the subscription active, which ensures that the relay has a updated view of the live edge?
- latest group number that the relay has available to deliver
- latest object number that the relay has available to deliver

TRACK_STATUS Message {
  Track Namespace (b),
  Track Name (b),
}

TRACK_STATUS_OK
{
  Track Namespace (b),
  Track Name (b),
  hasActiveSubscription(i),
  lastGroup(i),
  lastObject(i)
}

lastGroup and lastObject should be nullable, for the case in which hasActiveSubscription is false AND the relay has no objects from that track in cache. 

Open for debate is whether we should extend the response to also include the firstGroup and firstObject that the relay has in cache. To consider here is that the range may have holes and whether these need to be reported or not. Also to consider is whether returning range boundaries is expensive for the relay.

**Comment by afrind** [comment]
Individual Comment:

Does `hasActiveSubscription` distinguish between the cases of "relay is subscribed to a live track" and "relay is in the middle of cache-filling something old"?

**Comment by kixelated** [comment]
We should augment SUBSCRIBE_OK with this information, because it's necessary to map relative groups to absolute.

Could we reuse the messages instead of making a new one? I know it's a premature optimization, but what about `SUBSCRIBE end_object=0`?

**Comment by wilaw** [comment]
> Does hasActiveSubscription distinguish between the cases of "relay is subscribed to a live track" and "relay is in the middle of cache-filling something old"?

Yes. hasActiveSubscription has two requirements to be true:
1. The relay has an open subscription upstream that includes the head of the track
2. The relay has received at least one Object in response to that subscription

A relay that was cache-filling a hole in its archive should return false (because it doesn't know the true state of the live edge), as should a relay which has made a live subscription but has yet to receive any content. 

> We should augment SUBSCRIBE_OK with this information, because it's necessary to map relative groups to absolute.

Agree. This would enrich the SUBSCRIBE_OK response. It's still useful to have a separate ability to check STATUS without having to execute a SUBSCRIBE. The former gives you information about the live state. The latter commits you to receiving the track.

**Comment by kixelated** [comment]
`hasActiveSubscription` feels wrong to me. Is this meant to inform the client that the data is stale? Shouldn't the relay fetch the correct status instead of returning stale data?

**Comment by wilaw** [comment]
> Shouldn't the relay fetch the correct status instead of returning stale data?

I originally imagined this as a quick lookup that is completely local to the edge. You are just asking it to report the status of its cache, not to go back to the origin to validate. 

However we can expand it to be a lookup that validates with the origin. Currently the only way for a client to find out the live edge is for the edge relay to make a real subscription and for each intermediate relay to do the same. Having this message allows much lighter weight inspection. Think of it like a HEAD request against the track, versus a GET. 

If it goes back to origin, then the body should be modified to remove the `hasActiveSubscription`.

```
TRACK_STATUS_OK
{
Track Namespace (b),
Track Name (b),
lastGroup(i),
lastObject(i)
}
```

**Comment by kixelated** [comment]
It wouldn't need to go all the way to origin; just upstream until the first relay with an active subscription.

**Comment by kpugin** [comment]
what is the usecase for a client to do it without subscribing? Is that for clients to figure out "range" to subscribe for?

**Comment by wilaw** [comment]
After speaking this over with Kiril, the primary use case is an edge relay resolving relative subscription requests. For that there is a better solution which is described in https://github.com/moq-wg/moq-transport/issues/337. Closing this issue.
