### ISSUE TITLE
Can something be considered a MoQT relay if it does not terminate QUIC?

### ISSUE THREAD

**Issue by afrind** [moq-wg/moq-transport#336]
My understanding is that MoQ is always hop-by-hop encrypted by virtue of working over QUIC or WebTransport, and therefore a "relay" as described in the draft can only inspect Track/Group/Object metadata if it terminates QUIC.  The document should clarify the requirements.

**Comment by tmengKOP** [comment]
I agree with Alan. As a QUIC enthusiast, I guess the current draft implicitly suggests hop-by-hop QUIC termination at relay, e.g., which is necessary to enable cache at relay while having MOQT Message Type and OBJECT metadata as QUIC payload. Yet it is definitely more clarified for readers to explicitly see that information in an early section (e.g., sec 1.1.4).

**Comment by ianswett** [comment]
Given MoQ is over either QUIC or WebTransport, I believe it's impractical to restrict it to only QUIC based transports.

**Comment by afrind** [comment]
> Given MoQ is over either QUIC or WebTransport, I believe it's impractical to restrict it to only QUIC based transports.

The context of the question is whether one can build an MoQ relay that can view object properties without terminating the TLS session underpinning MoQ or WebTransport (eg an untrusted middlebox).
