### ISSUE TITLE
Additional Subscribe Errors

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#347]
I woudld think that "track doesn't exist" and "unauthorized" would be useful error codes, but they don't seem to fit in 'Invalid Range' or 'Retry Track Alias'.

**Comment by ianswett** [comment]
As discussed today, it'd be nice to have one indicating "Timeout".

**Comment by martinduke** [comment]
Assigned to @kixelated as C-in-C of error codes.

**Comment by ianswett** [comment]
Fixed by #529
