### ISSUE TITLE
SUBSCRIBE needs Num Parameters field

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#349]
if there are going to be "track request parameters" in subscribe, we need a way of indicating that it is present. Presumably via a NumParameters field.

**Comment by afrind** [comment]
Individual Comment: 

Can you use the message length?  eg: if there are any bytes remaining after parsing required fields, parse another param?

**Comment by martinduke** [comment]
There is no message length, right? Or did that come back?

**Comment by afrind** [comment]
You are right, there's no message length, and this looks like an oversight or mis-merge?  Can you make a PR to add Num Parameters, and perhaps the group will agree to set the interop target to draft-02 + that PR?

**Comment by fluffy** [comment]
Reading RFC 9000 section 1.3, I thought the syuntax "x (L) ..." meant we would have zero or more and it included the counter of how many in the encoding. I could be missing the boat here but not seeing why we have the number twice on the wire. I am always confused about the syntax used in RFC 9000 so I probably confused here but someone walk me through it.

**Comment by martinduke** [comment]
Yes, some of these 9000 formats are very confusing, and I had to look again.

The format in the MOQT draft is 'Parameters (..) ...'. I can't really parse the definitions in 1.3, but this notation occurs in two places in 9000. One is ACK ranges, and ACKs have an explicit ack_range_count field. 

In any case, there are several other places (SETUP, ANNOUNCE) where we have the field listed there. So:
1) I think the notation is wrong
2) Even if it isn't we should be consistent
3) Even if it isn't, it impedes understanding and an explicit listing would be better.
