### ISSUE TITLE
QUIC Streams and Datagrams support

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#35]
Creating this issue to reflect WG discussions. Not sure what's the right next steps, but would be good as a placeholder to further discussions

**Comment by kixelated** [comment]
I filed #38 for a common issue brought up with streams.

**Comment by fluffy** [comment]
I definitely want to play with both stream and datagrams and see what the performance looks like. The more we dig into this, the less clear it all is to me. When I was playing with it before I was not doing the WARP new is higher priority stuff and that changes things in a good way. I think there are a few thought experiments I am interested in and perhaps trying to collect data on. 

One: On high latency, high packet loss connections, does the time to end a stream result in significantly less "good put". 

Two: On a relay that was fanning out to to 10k clients that were each getting a 4 mbps stream with normal packet loss and say 50 ms RTT,  is memory use of duplicate copies of the data before it is ack'd in each of the 10k connections a problem? Back of the envelope would suggest it is no big deal but like to play with a few of theses things more. 

Totally in favour of collecting more data and talking about this before making a decision.

**Comment by VMatrix1900** [comment]
> Two: On a relay that was fanning out to to 10k clients that were each getting a 4 mbps stream with normal packet loss and say 50 ms RTT, is memory use of duplicate copies of the data before it is ack'd in each of the 10k connections a problem? Back of the envelope would suggest it is no big deal but like to play with a few of theses things more.
This reminds of the Reliable Multicast Transport(rmt) working group which tries to solve the fan-in ack scalability problem during 2000-2013. It uses NACK and FEC to reduce the feedback frequency and designs a feedback suppression mechanism to deal with the extreme case. Maybe it is time to re-examine the problem.

**Comment by afrind** [comment]
> is memory use of duplicate copies of the data before it is ack'd in each of the 10k connections a problem

This is kind of dependent on how your QUIC API works.  mvfst for example doesn't have to exclusively own data written to the transport, but rather owns relatively small descriptors that reference count underlying memory.

**Comment by ianswett** [comment]
My proposed resolution to this would be that the decision to transmit object(s) over a Stream or Datagram is a decision made by the publisher based on whether the connection supports datagrams, the MTU, and the size of the object(s).

This also relates to the object model, since I suspect datagrams make the most sense when a single Object is mapped to a single stream.

**Comment by suhasHere** [comment]
Agree that this goes back to Object Model mapping discussion. Having publisher being able to make that choice will be important for different classes of applications over moqt.

**Comment by kixelated** [comment]
Yeah, the publisher can decide if it wants to use a datagram and relays would maintain that decision. A few caveats though:

* **Max MTU of 1200**. Please don't make me refragment datagrams on relays like RTP.
* **Fire-and-forget**. Don't reinvent QUIC streams with retransmissions, reassembly, acknowledgments, flow control, etc.

**Comment by ianswett** [comment]
I'd like to separate the decision of how to bundle things from whether data is sent over streams or datagrams.  They can be made to have identical properties in terms of reliability, it's just a matter of implementation.

Is there a reason to believe transforming from one to the other causes undue cost?  And if it does, could we just say not to negotiate datagram support if you don't want to do the transformation?  This would allow us to experiment and see when they work well without requiring anyone to support them.

**Comment by afrind** [comment]
draft-02 has a mechanism for datagram support.
