### ISSUE TITLE
Problems with RelativeNext subscriptions

### ISSUE THREAD

**Issue by wilaw** [moq-wg/moq-transport#353]
1. Consider the following sequence of groups and objects, some already produced , some that will be produced in the future. The largest group ID is currently 23 and the largest object ID is 3 (it also happens to be the last object in the group). 

![Screenshot 2024-02-01 at 9 15 24 PM](https://github.com/moq-wg/moq-transport/assets/2762250/421edef1-3110-4a05-8544-1e4ec2662423)

Our definitions for RelativePrevious and RelativeNext are shown here. 

> RelativePrevious (0x2): Value is a delta from the largest sequence. 0 is the largest sequence, 1 is the largest sequence - 1, and so on.
> RelativeNext (0x3): Value is a delta from the largest sequence. 0 is the largest sequence + 1, 1 is the largest sequence + 2, and so on.

Example 6.4.3.1 for 'now' shows

```
Start Group: Mode=RelativePrevious, Value=0
Start Object: Mode=RelateiveNext, Value=0
End Group: Mode=None
End Object: Mode=None

StartGroup=Largest Group
StartObject=Largest Object + 1
```

In our example, largest group is 23, however Largest Object + 1 is 4, which does not exist. We need to adjust the definition of RelativeNext to allow for the fact that the next object may be in a different group.

2. There may be some players who simply want the relay to send the next available Object, in this example Object 0 of group 24. 

There is no current way to reliably ask for this, because StartGroup mode cannot be 'none', and we don't know which group that object will belong to. It may be in the currently largest group, or it may be in the next group. 

A solution here would be to relax the constraint that StartGroup mode cannot be 'none'. If we then request

```
Start Group: Mode=None
Start Object: Mode=RelativeNext, Value=0
```

it would instruct the relay "Send me your next object, no matter which group it belongs to".

5. In 6.4.3 we have examples titled 'Now',  'Current', "previous" and 'Next".  

'Now',  'Current'  are synonymous to most readers. We need to better titles to illustrate what is actually being requested here. Additionally, 
"Previous' doesn't indicate whether we want the previous group, or previous object. Similarly for next.

**Comment by afrind** [comment]
Individual Comment: 

You are right that the example (and the text likely) don't show the full range of possibilities for what the next object will be.  The intent was that Start = Prev/0, Next/0 will get you the next object, which could be any object in the current group greater than largest, or the first object in the next group.  This is how my implementation handles it.  

I don't see a way to get *only* the next object in the current draft, however, because of the ambiguity you describe.
