### ISSUE TITLE
Objects with unknown length and forwarding preferences

### ISSUE THREAD

**Issue by vasilvv** [moq-wg/moq-transport#355]
In our current encoding, you can stream objects without knowing their length in advance if your forwarding preference is Object or Datagram, but not if it's Track or Stream (since those require explicit lengths in the front).  I feel like those two aspects should not be tied: we should either support or not support streaming for all preferences.

**Comment by afrind** [comment]
Individual Comment:

In order to stream multiple objects with unknown lengths in a multi-object stream, you'd need additional framing.    

Alternately, we could create single-object variants of the TRACK and GROUP stream header.

**Comment by kixelated** [comment]
I agree it's weird to have a mix of unframed and framed messages.

While I prefer unframed streams... I think we should state that MoQ objects are always framed, represent a single point in time, and have a known length. It's an optimization to withhold the length in the datagram and dedicated stream case but maybe we should include it.

**Comment by fluffy** [comment]
In meeting we decided add a length to everything. We can add extension later to have no length if we need ( Thanks to Mike E for suggestion )
