### ISSUE TITLE
SUBSCRIBE_FIN/RST for old subscriptions

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#356]
Sections 6.8 and 6.9 strongly imply that SUBSCRIBE_FIN/RST are sent at the true end of the track. So are they not sent at the conclusion of a SUBSCRIBE that does not cover the end of the track?

For example, if the last object of a track is (10, 12), and there's one subscribe for (4,0) to (5, 100)

Is there a SUBSCRIBE_FIN?

If not, how does the subscriber know that in fact (5, 60) is the last object in that subscription?

If so, does Final Group and Final Object refer to the last object in the subscription?

**Comment by afrind** [comment]
Individual Comment: 

Putting my HTTP hat on for a second, when you ask for something with unknown length, you infer from a graceful termination that the last thing you got was the true end of that resource.  If you send a range request, the graceful termination at the end does not convey that the last thing was the true end.  Once the object expires, you can issue another request to the same name and potentially get a totally different thing.

Does this model work for moq, or do we need something different?

**Comment by martinduke** [comment]
There are three different things you might want to communicate to a receiver at the end of the subscribe:

1) You got all of the objects in the range;
2) You got almost all of the objects, but some were dropped for latency/bandwidth reasons
3) The track was truncated for some reason

and possibly, 4?
4) You got everything I have but i'm not sure if that's everything

**Comment by ianswett** [comment]
#345 is somewhat relevant to this issue.
