### ISSUE TITLE
Objects before SUBSCRIBE_OK

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#357]
Since they're on different streams, an object can arrive before its SUBSCRIBE_OK. This is easy to process because the Subscribe ID and Track Alias must have been the ones that the subscriber chose.

What if the publisher then sends a SUBSCRIBE_ERROR? Is this valid behavior or an error?

(If it weren't for the Expires field, SUBSCRIBE_OK would be entirely redundant and we could get rid of it.)

**Comment by afrind** [comment]
Individual Comment:

This is covered a bit in #310 and Luke expressed a desire to document the full state machine in #237.  My read is that you can't send objects before SUBSCRIBE OK (but they can arrive out of order).  I don't think you can send SUBSCRIBE_ERROR after SUBSCRIBE_OK (objects or no objects), instead, use SUBSCRIBE_RST?

**Comment by martinduke** [comment]
I agree that SUBSCRIBE_ERROR cannot follow SUBSCRIBE_OK.

I think you're saying that if Objects are in flight, then SUBSCRIBE_OK must be as well, so a SUBSCRIBE_ERROR would in itself be an error. That sounds reasonable to me.

**Comment by ianswett** [comment]
We're clear that only one of SUBSCRIBE_OK or SUBSCRIBE_ERROR can be sent:

> The subscriber making the subscribe request is notified of the result of
the subscription, via SUBSCRIBE_OK ({{message-subscribe-ok}}) or the
SUBSCRIBE_ERROR {{message-subscribe-error}} control message.
The entity receiving the SUBSCRIBE MUST send only a single response to
a given SUBSCRIBE of either SUBSCRIBE_OK or SUBSCRIBE_ERROR.

I wrote #387 to clarify that you can't send objects and a SUBSCRIBE_ERROR.
