### ISSUE TITLE
'Expires' in SUBSCRIBE_OK makes it unclear what the final group and object will be

### ISSUE THREAD

**Issue by ianswett** [moq-wg/moq-transport#390]
Subscriptions always end with either SUBSCRIBE_FIN or SUBSCRIBE_RESET, except when they Expire and then no control message is sent.  This complicates the state machine and adds another case to handle.

The subscriber needs to start a timer or something similar to know when the subscription will end, and it doesn't get to know the final group or object ID.

**Comment by kixelated** [comment]
I'd like to get rid of `expires`, but my thouht was that it's a signal to SUBSCRIBE again before the timeout to avoid interruption. Otherwise, there would be a SUBSCRIBE_RESET with an "expired" error code containing the final group/object.

**Comment by ianswett** [comment]
I agree that a subscriber can deal with this field, but I don't know what purpose it serves for the publisher/relay?  It's different from an idle connection timeout, because assuming there is data flowing for the subscription, it would never go idle.

Unlike QUIC, I don't see value in having a 'silent close' for subscriptions, because typically we expect subscriptions to have data flowing at a somewhat regular interval.

Also, there's no guarantee that the subscription will last until the expiry time, it can always end early with SUBSCRIBE_FIN or SUBSCRIBE_RESET.

**Comment by fluffy** [comment]
Would the solution to this be when the relay expires a subscription, it sends a control message ?  This might all become clearer once we figure out re authentication but at a high level, I want some way that the relays can clean up state on a time line that is under relay control particularly when poorly implemented clients make subscriptions.

**Comment by afrind** [comment]
I think this was resolved by #406 - 


> A subscription remains active until the publisher of the track terminates the track with a SUBSCRIBE_DONE (see {{message-subscribe-done}}).
