### ISSUE TITLE
Current naming is hard to keep track of <BIKESHED> 

### ISSUE THREAD

**Issue by fluffy** [moq-wg/moq-transport#398]
Propose names from my understanding of discussion call 

Announce (send by publisher)  , Annouce_OK, Annouce_Error
UnAnnounce (send by publisher)  UnAnnounce_OK, UnAnnounce_Error 
Annouce_End ( sent by thing that received Annouce) , AnnouceEnd_OK, AnnouceEnd_OK

Subscribe (send by subscriber)  , Subscribe_OK,  Subscribe_Error
UnSubscribe (send by subscriber)  , Subscribe_OK,  Subscribe_Error
Subscribe_End (send by thing that received subscriber), Subscribe_OK,  Subscribe_Error

Mostly trying to get rid of FIN / RST and have different names for the messages that flow in opposite directions.

**Comment by kixelated** [comment]
I don't like the name of the _ERROR messages. And I'd rather have one message that transitions to the terminal state, with an optional error code.

IMO the subscription flow:
```
  -> SUBSCRIBE
[ <- SUBSCRIBE_OK    ]
[ -> SUBSCRIBE_STOP  ]
  <- SUBSCRIBE_CLOSE
```

And the ANNOUNCE flow mirrors:
```
  -> ANNOUNCE
[ <- ANNOUNCE_OK    ]
[ -> ANNOUNCE_STOP  ]
  <- ANNOUNCE_CLOSE
```

The brackets mean a message is optional. The sender is responsible for creating and the receiver is responsible for closing, possibly at the bequest of the 
sender (like QUIC's STOP_SENDING).

**Comment by ianswett** [comment]
#392 has been merged, adding yet another term (CANCEL), but I figured we'd clean that up with this issue.

**Comment by vasilvv** [comment]
Since we are bikeshedding, I prefer ANNOUNCE_RESCIND instead of CANCEL, since an announce is more of a declarative statement than an active request from the sender.

**Comment by kixelated** [comment]
Heh and UNANNOUNCE and UNSUBSCRIBE stick out because they don't share the same prefix.

**Comment by ianswett** [comment]
I'm leaning towards CLOSED instead of CLOSE because CLOSE implies its a requested action, so to me SUBSCRIBE_CLOSE sounds like something the subscriber would send, not the publisher.

For a similar reason, I like CANCEL slightly better than STOP, but both work.

UNANNOUNCE and UNSUBSCRIBE are good words, but I think it's better to follow a pattern in this case and I like @kixelated sequence of messages.

**Comment by fluffy** [comment]
So to add an OK, we need to add another state. The question for me is what is the use case where we need to deliver that information in the end of the subscribe.

**Comment by fluffy** [comment]
This discusion is probably easier looking at #402 state machine diagrams
