### ISSUE TITLE
What happens if we get OBJECT_DATAGRAM on a Stream?

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#410]
Now that Datagram is no longer just a suggestion, should there be some sort of error if we get OBJECT_DATAGRAM on a Stream?

**Comment by kixelated** [comment]
Absolutely, and it's something I'd like to address in #407

**Comment by fluffy** [comment]
I view this as "protocol error" and any time we get that we should tear down the QUIC connection with appropriate error.

**Comment by huitema** [comment]
There is a simple way to not have that error: just do not allocate a number for the type "OBJECT_DATAGRAM", and state that the content of a datagram is implicitly of state "OBJECT_DATAGRAM". Also saves one byte per datagram.
