### ISSUE TITLE
Controlling encoding parameters on the receive side

### ISSUE THREAD

**Issue by vasilvv** [moq-wg/moq-transport#42]
Currently, all of the parameters like expiration time for layers are always configured by the sender.  This makes sense in most cases (when doing delivery to the CDN or to an end user), however, in case of ingestion, the receiver might have a better understanding of, say, when the layers should expire.  We should provide a way for the receiver to give hints to the encoder.

**Comment by kixelated** [comment]
Twitch would love the ability to influence the encoder on the server side. Stuff like choosing the renditions, bitrate, codec, CBR/VBR, etc.

**Comment by kixelated** [comment]
Meta has asked for something similar too. Although this doesn't need to be part of MoQ; it could be as simple as a JSON file at a known endpoint.

**Comment by VMatrix1900** [comment]
+1. The receiver has the final say on the QoE. Feeding the QoE back to sender can help the sender side optimization. Like [QoE feedback in this draft](https://datatracker.ietf.org/doc/draft-ma-quic-mpqoe/).

**Comment by afrind** [comment]
Delivery timeouts are coming (#449) which are a way for the subscriber to influence the publisher timeouts in the ingest case.  As for codecs, etc, I think the current model is for the broadcaster to advertise all the options via a catalog and let the ingest point subscribe.  Closing for now, please open a new issue if there is still something to fix here.
