### ISSUE TITLE
Are end-of-group messages mandatory?

### ISSUE THREAD

**Issue by afrind** [moq-wg/moq-transport#442]
#429 introduced the Status field for Objects, which can have a value that signals the end of a group (0x3). 

The draft states:

> This is sent right after the last object in the group. 

I read this to mean that whenever a publisher publishes the last object in a group, it also publishes the end-of-group marker (eg: it is mandatory).   However, it seems like this might create high overhead - eg in an audio only track where every sample is its own group.

For a fanout relay handling group-per-stream tracks, the end of group marker is a signal that it can close the downstream streams.  Yes, the relay needs a timeout as well, to catch malicious or buggy producers, but I'd prefer that be the rare, and proactively clean up the state since it could be quite large.

The other modes seem less critical for a relay, I think? However, I worry about interoperability between producers and consumers if we don't make it required in other stream modes.  That could be part of a streaming format specification rather than the core transport.

Given that datagrams are inherently unreliable, I don't know that we need to mandate end-of-group markers there.

**Comment by ianswett** [comment]
I think the cleanest option is to require them and make them mandatory, unless something like an OBJECTS_DROPPED message is sent.  We can make the wire encoding very efficient as long as the producer knows that an Object is the final Object in a group when it's published.

I think end of track is equally important, but there are no efficiency concerns there.

**Comment by fluffy** [comment]
I don't think even know what saying they are mandatory would even mean at the  transport level.  Can a producer wait forever before sending the end of group ? Can anyone else rely on receiving the end of group with a given window ? what would break if not sent.  

I do see how a something like loc or warp would say how they have to be used but transport seems like the wrong level to say if they are used or not.   If sending end of group increase the bandwidth of low bit rate audio by a non trivial amount, then I dont think they will be used in cases where the applications know that there is only one audio packet per group.

**Comment by afrind** [comment]
Individual Comment:

> I don't think even know what saying they are mandatory would even mean at the transport level. Can a producer wait forever before sending the end of group ? Can anyone else rely on receiving the end of group with a given window ? what would break if not sent.

See the original post:

> For a fanout relay handling group-per-stream tracks, the end of group marker is a signal that it can close the downstream streams. Yes, the relay needs a timeout as well, to catch malicious or buggy producers, but I'd prefer that be the rare, and proactively clean up the state since it could be quite large.

Could we have "publishers SHOULD send end-of-group markers when using group-per-stream", with text explaining why this is helpful for relay state management? 

I'm assuming audio is datagrams so it's not impacted.  Knowing the end of group in stream-per-track is obvious (the group number changes).  In stream-per-object it might be useful to the receiver but I'm not sure it's critical at the relay right now, though a use case may emerge as we move forward.

**Comment by fluffy** [comment]
I guess the part I am missing is what does the relay do with this information and how it is useful.

**Comment by afrind** [comment]
> I guess the part I am missing is what does the relay do with this information and how it is useful.

Assume a fan-out relay with one publishing track fanning out to 1 million subscribers.

publisher opens a stream for group 0, sends objects 0
relay opens a stream for each of 1 million downstream subscribers and pushes object 0
publisher sends a FIN for its group stream

Should the relay close the 1 million downstream streams now?

If the publisher sends the end-of-group marker, it is explicit that the relay can close these streams immediately (there is also a timer-based cleanup path for publisher crashes etc).  I don't think we should infer end-of-group from QUIC FIN - I imagine there may be some high availability scenarios where a redundant publisher could take over, and hence prefer an explicit signal. I doubt the overhead of the end-of-group marker will make a difference in this scenario -- it's a handful of bytes that will either go in the packet with the final object or the packet that had the FIN.

**Comment by fluffy** [comment]
Just want to say that I find Alan's point above really convincing. However, this does make me want to have a very low bandwidth impact way to solve this.  I also am wondering if better way of managing streams is just close ones that have not been used recently. I think we need some more thought on how relays close streams.

**Comment by afrind** [comment]
Individual Comment: 

Another clear use case is when a subscription ends at an absolute group/object in stream-per-group (via SUBSCRIBE_UPDATE or Absolute Range).  The publisher will FIN the stream but it is not necessarily the end-of-group.

**Comment by kixcord** [comment]
> I don't think we should infer end-of-group from QUIC FIN - I imagine there may be some high availability scenarios where a redundant publisher could take over, and hence prefer an explicit signal.

I want to make sure that you're not proposing N streams per group. It MUST be a fatal error to open a second for the same group/track within a session. Otherwise, it means a generic subscriber needs to support multiple, potentially simultaneous, streams for each group/track and stitch them together, defeating the purpose of 1 stream per X.

IMO if a publisher crashes, then the stream should be considered reset. However, a relay could subscribe to a redundant publisher to avoid reseting the stream for all downstreams. Or the relay could have an active subscription to both publishers and merge them together with business logic. 

But two streams per group/track _within the same session_ is just wrong and should not be supported.

**Comment by vasilvv** [comment]
> It MUST be a fatal error to open a second for the same group/track within a session. 

If the client issues two subscribes, one for `(16, 10)...(16, 15)`, and another for `(16, 20)...(16, 25)`, those have to go onto different streams.  I'm not sure I see an alternative here.

**Comment by afrind** [comment]
Individual Comment: 

I'm not proposing a fan-in model.  I was thinking more like some relays might have a sorted list of publisher sessions for a given namespace, and switch to B if A has to shutdown.

The draft currently says this:

> A publisher SHOULD NOT open more than one multi-object stream at a time with the same stream header message type and fields.

This works for Victor's case because the subscriptions have different subscribe IDs in the header.  However the "at a time" language means theoretically the publisher can close the stream for one group and open a new stream for the same group within the same subscription without violating the spec, though I can't imaging what the advantage of doing that is?  Maybe to save resources if no objects will be published for a long time?

**Comment by kixelated** [comment]
> > It MUST be a fatal error to open a second for the same group/track within a session.
> 
> If the client issues two subscribes, one for `(16, 10)...(16, 15)`, and another for `(16, 20)...(16, 25)`, those have to go onto different streams. I'm not sure I see an alternative here.

Sorry I meant within a subscription, not session.

**Comment by afrind** [comment]
Individual Comment:

In draft-06, I'm no longer most concerned about end-of-group messages, but end-of-subgroup.

These are more problematic than end-of-group messages, because each requires a valid object ID.  Applications that can produce stream-per-object and stream-per-group versions of the same track will have divergent object ID mappings for the same content, or gaps.

I'm now convinced stream FIN can replace 'end-of-subgroup'.  To terminate a subgroup when you don't know if you have the end, use Reset Stream, or preferably Reliable Reset Stream.  Reset Stream alone can result in valid transmitted objects being truncated or dropped completely by the receiver, which is harsh if the only intent was to communicate 'I'm closing this and don't know if there's more or not'.  Reliable Reset Stream covers the happy medium of "deliver everything I wrote, but don't signal completion".  

Taking a dependency on RRS in MoQ has some implications we can talk through.  If we're reluctant to do so, another option is replace end-of-subgroup with an optional "To Be Continued" status, which the publisher or relay inserts at the end of subgroup prior to FIN when it wants all data delivered but has not definitively know if more exists (eg: publisher QUIC connection to relay was dropped).  To Be Continued would always have object ID=<sentinel>, or otherwise be ignored.

**Comment by martinduke** [comment]
see https://docs.google.com/presentation/d/1s1r5-PB13kdle_3ozCd2xOylSaGbEcneKji092hVpJA/edit?usp=sharing for some thoughts on how to solve this

**Comment by ianswett** [comment]
I think this is clarified by #589
