### ISSUE TITLE
SETUP Parameters Key vs Type

### ISSUE THREAD

**Issue by TimEvens** [moq-wg/moq-transport#460]
Section 6.2.2.1 (Role) and section 6.2.2.2 (PATH) indicate `key 0x00` and `key 0x01`.  Shouldn't key be `type`?

**Comment by huitema** [comment]
The "parameters" syntax is defined in section 6.1 as:
~~~
   Parameter {
     Parameter Type (i),
     Parameter Length (i),
     Parameter Value (..),
   }
  ~~~
We should be consistent, and refer to "Parameter Type 0x1", etc.
