### ISSUE TITLE
Limits on the amount of buffered data

### ISSUE THREAD

**Issue by vasilvv** [moq-wg/moq-transport#462]
If the relay is sending data to a subscriber, and the link between the subscriber and the relay cannot sustain the bitrate of the track, eventually the relay will have to buffer more and more data.  At some point, the relay would have to drop the data; we should specify how that happens (lowest priority stream gets dropped first?).

**Comment by afrind** [comment]
Individual Comment:

+1  We need to specify what happens in this case.  I think there's two parts: 

1) selecting what gets dropped (this is a priority question)
2) the mechanism for dropping (stream resets, etc).

**Comment by englishm** [comment]
+1

Expanding Alan's list, I think we should determine:

- (1a?) valid boundaries for dropping data (group? object? byte? bit?)
- (2a?) under what circumstances the subscriber needs to be informed of the dropped data (do we need different verbs with different semantics in this case, e.g. fetch/subscribe? is dropping data always permitted and something all subscribers must be able to tolerate?)
- (2b?) the means of informing subscribers of dropped data (implied or explicit)
