### ISSUE TITLE
Object Status makes me sad

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#466]
- Requires an additional stream per group, when using a stream per object.
- Makes objects "nullable" in the API (empty payload != status 0x1)
- status != 0 wastes a byte on a zeroed size

I think we should use a GROUP_END and TRACK_END message instead of overloading OBJECT. And an application can use an empty payload to indicate gaps... or whatever encoding it wants.

**Comment by afrind** [comment]
Individual Comment:

> Requires an additional stream per group, when using a stream per object.

This is annoying.  #442 asks the question if publishers are required to send end of group messages.

> Makes objects "nullable" in the API (empty payload != status 0x1)

Can you explain more? Do you mean that it is now possible to have a "Normal" object with an empty body and you would prefer this was not allowed?  

Keep in mind the API is not what is standardized, and you can make an API as opinionated as you want.  Many HTTP APIs don't give you access to the full protocol (streaming post body, trailers, and push are commonly omitted features).

> status != 0 wastes a byte on a zeroed size

This seems fixable by defining the length field as only present on non-zero status?

> we should use a GROUP_END and TRACK_END message ...
 
One important function of Object Status is the ability to communicate that an object is permanently unavailable.

**Comment by kixelated** [comment]
> Can you explain more? Do you mean that it is now possible to have a "Normal" object with an empty body and you would prefer this was not allowed?
>
> Keep in mind the API is not what is standardized, and you can make an API as opinionated as you want. Many HTTP APIs don't give you access to the full protocol (streaming post body, trailers, and push are commonly omitted features).

Yeah exactly, a MoQ API should not allow applications to set the object status manually because it's ripe for misuse.

To support status=0x1, I would design an API using `std::optional<std::vector<uint8_t>> payload` (ur welcome for C++).

But why does the application need both nullopt and an empty payload? What's the use case? What's the difference between an empty payload and status 0x1?

> > status != 0 wastes a byte on a zeroed size
> 
> This seems fixable by defining the length field as only present on non-zero status?

Aka make the status codes separate message types. They're still on the "data plane" as unidirectional streams.

> > we should use a GROUP_END and TRACK_END message ...
> 
> One important function of Object Status is the ability to communicate that an object is permanently unavailable.

No, it means that the object never existed from the application's point of view. We agreed that we needed a separate mechanism for dropping objects, such that an object status should be immutable.

**Comment by afrind** [comment]
Individual Comment:

> Yeah exactly, a MoQ API should not allow applications to set the object status manually because it's ripe for misuse.

> To support status=0x1, I would design an API using std::optional<std::vector<uint8_t>> payload (ur welcome for C++).

I haven't written the code yet, but I'd probably just have two APIs?  `publishObject(header, payload)` and `publishPlaceholder(header, status)`.  I write lots of APIs that are ripe for abuse though :D 

> No, it means that the object never existed from the application's point of view. 

That's not what draft-04 says:

> Indicates Object does not exist. Indicates that this object does not exist at any publisher and it will not be published in the future. This SHOULD be cached.

Seems like an Original publisher could send a status=0 obj at time T and if someone asks at time T + N, it could send status=0x1.

**Comment by fluffy** [comment]
We have been around this countless times now. Your proposal does not work. Imagine I something is doing stream per track and the publisher looses wifi for a fraction of a second then reconnects. At this point all the end subscribers think the track as ended, disconnect, and will not reconnect.

**Comment by kixelated** [comment]
> We have been around this countless times now. Your proposal does not work. Imagine I something is doing stream per track and the publisher looses wifi for a fraction of a second then reconnects. At this point all the end subscribers think the track as ended, disconnect, and will not reconnect.

@fluffy I don't understand, can you explain? Are you suggesting that the relay inserts status=0x1 objects on a reconnection?

**Comment by martinduke** [comment]
IMO the case for "Object/Group does not exist" is pretty clear-cut: does it make sense for the receiver to wait on this missing object ID or not? Unless of course, we get rid of Object ID gaps, which I would be fine with.

It would be useful to be a bit more specific about the use case for EndOfGroup. It's useful to confirm that you got everything in a group, but the negative signal is not getting the EndOfGroup message, but this is more efficiently one by just attaching some sort of FIN bit to the last normal Object.

The added value of the EndOfGroup object is if it's useful to know the highest Object ID when the receiver doesn't have all the intervening objects; the non-normal object is cheaper to send, if it ought to be sent. I'm not sure what I would do with this information, as a receiver. So I'd be in favor of replacing this message with an end-of-group message type or flag.

**Comment by martinduke** [comment]
I would also add that Peeps, should we adopt them, makes EndOfGroup a bit worse. Strictly speaking, EndOfGroup is independent and therefore gets its own peep, which is gross.

You could make it dependent on the highest Object ID, which saves a stream but again calls into question why we need this message at all.
