### ISSUE TITLE
SUBSCRIBE_UPDATE response/error handling

### ISSUE THREAD

**Issue by roticv** [moq-wg/moq-transport#467]
Draft 04 currently doesn't mention about sending any response when the SUBSCRIBE_UPDATE is successful or when it fails even though the draft hints on possible failures

>   If Objects before the start or after the end of the current
>   subscription are needed, a separate subscription can be made.  The
>   start Object MUST NOT decrease and when it increases, there is no
>   guarantee that a publisher will not have already sent Objects before
>   the new start Object.  The end Object MUST NOT increase and when it
>   decreases, there is no guarantee that a publisher will not have
>   already sent Objects after the new end Object.

The above suggests that an error should be sent to inform the client that it is making invalid subscription updates.

**Comment by ianswett** [comment]
#455 documents some other aspects of SUBSCRIBE_UPDATE that are underspecified.
