### ISSUE TITLE
Challenges with being too vague on `subscribe_id` and `track_alias`

### ISSUE THREAD

**Issue by TimEvens** [moq-wg/moq-transport#482]
As I read the draft, `SUBSCRIBE_ID` is the distinguisher of a given subscription. `TRACK_ALIAS`  is made unique for a subscription state by indicating *"If the Track Alias is already in use, the publisher **MUST** close the session with a Duplicate Track Alias error."* 

The `TRACK_ALIAS` is mentioned as *"A session specific identifier for the track."*. It is initially set by the subscriber, where the publisher **MAY** reject... likely not if it wants to avoid long subscribe times.   The draft does not indicate that the track alias is a hash of track `namespace + name` or not.  

If the client implementation uses a sequence ID for both subscribe ID and track alias, then it could result in duplicate subscribes that would result in the relay building state, propagating the subscribe toward the publisher to solicit a response of OK/ERROR. In some implementations that support headless publishers, the relay would send a subscribe OK immediately.

The edge relay that has the connection to the publisher performs state compression of subscribes, but that's only at the `track_alias` level per the draft.  In this case, the track alias is different, resulting in a new subscribe (duplicate when looking at the `namespace+name`) being created to the publisher. 

The publisher receives the subscribe with a new `SUBSCRIBE_ID` and `TRACK_ALIAS` and starts to publish data objects using the `SUBSCRIBE_ID` and `TRACK_ALIAS` that match internally the **track** `namespace + name`.  If one or more clients do this repeatedly, it would result in all relays and the actual publisher itself sending duplicate data that matches `namespace + name`.  

Below diagram illustrates the above.

```mermaid
sequenceDiagram
    actor P as Actual Publisher
    participant R1 as Relay 1
    participant R2 as Relay 2
    actor S as Lazy Subscriber

    S ->>R2: SUBSCRIBE (id=5, space=clock, name=second, alias=100)
    R2-->>S: SUBSCRIBE_OK (id=5, alias=100)
    R2 ->>R1:  SUBSCRIBE (id=99, space=clock, name=second, alias=9901)
    R1 -->>R2: SUBSCRIBE_OK (id=99, alias=9901)
    R1 ->>P:  SUBSCRIBE (id=14, space=clock, name=second, alias=31)
    P -->>R1: SUBSCRIBE_OK (id=14, alias=31)
    P -) R1: OBJECT (id=14, alias=31, g=1, id=1)
    R1 -)R2: OBJECT (id=99, alias=9901,  g=1, id=1)
    R2 -)S: OBJECT (id=5, alias=100, g=1, id=1)
    Note right of P: Objects are flowing for namespace = clock, name = second
    Note left of S: Lazy subscriber sends another SUBSCRIBE

    S ->>R2: SUBSCRIBE (id=6, space=clock, name=second, alias=101)
    R2-->>S: SUBSCRIBE_OK (id=6, alias=101)
    R2 ->>R1:  SUBSCRIBE (id=100, space=clock, name=second, alias=9902)
    R1 -->>R2: SUBSCRIBE_OK (id=100, alias=9902)
    R1 ->>P:  SUBSCRIBE (id=15, space=clock, name=second, alias=32)
    P -->>R1: SUBSCRIBE_OK (id=15, alias=32)


    P -) R1: OBJECT (id=14, alias=31, g=1, id=2)
    R1 -)R2: OBJECT (id=99, alias=9901,  g=1, id=2)
    R2 -)S: OBJECT (id=5, alias=100, g=1, id=2)

   Note left of S: Below object is duplicate due to duplicate subscribes for same namespace + name

    P -) R1: OBJECT (id=15, alias=32, g=1, id=2)
    R1 -)R2: OBJECT (id=100, alias=9902,  g=1, id=2)
    R2 -)S: OBJECT (id=6, alias=101, g=1, id=2)

```

### Resolutions

I'm sure there are many reasonable fixes for this... below are a few. 

#### (1) Update protocol spec to make track namespace and name active at one time only per client/subscriber session

This would change the verbiage of duplicate track detection to perform duplication check on `namespace` and `name` instead of only on track alias.  The state machine for subscribe **SHOULD** change to move `TRACK_ALIAS` from `SUBSCRIBE` **TO** `SUBSCRIBE_OK`.   This simplifies the state machine by reducing the complexity in:

* detection and elimination of duplicate subscribes
* eliminating the challenges with having to deal with `SUBSCRIBE_ERROR=Duplicate Track Alias` trial and error responses

#### (2) Hash **Track** `namespace` and `name`
A hash of namespace and name would allow for the duplicate track detection to work per draft, but... Track alias has a max value of 62 bits. Collisions are the largest pitfall for using a hash of two values.

#### (3) Registry/directory service of **Track** `namespace` and `name`
Registry/directory service could act as gatekeeper of track aliases.  While this would work, it introduces another micro service for a simple pub/sub, which isn't great. It will also slow the subscribe process down.  Many other issues will likely arise with this approach.

**Comment by suhasHere** [comment]
> If the client implementation uses a sequence ID for both subscribe ID and track alias, then it could result in duplicate subscribes that would result in the relay building state, propagating the subscribe toward the publisher to solicit a response of OK/ERROR

I don't understand duplicate subscribes issue here ? can you please elaborate .

**Comment by suhasHere** [comment]
If a subscriber sends 2 subscriptions for the same track to a publisher ( ignoring relays for a bit here and also ignoring any form if Ids ), what should be the expected behavior of the publisher ? 

There are few  options 
1. Publisher sends 2 copies of the objects (wherever they overlap) 
2. Publisher rejects the second subscribe since it is in the same connection 
3. Publisher sends only 1 copy of the overlapping objects 

What is in draft today allows for 1.

**Comment by TimEvens** [comment]
Clarification on relay vs publisher needs to be distinct here. When discussing this topic, we need to be distinct on is the request for a range of objects (aka fetch operation where there is a start and finish?) or subscribe to live stream where there is no known end?  

Some of the challenges here are introduced with the MOQT decision to overload `subscribe` to support both fetch operation and subscribe to live stream, possibility starting at X.  

In the case of fetch operation, subscribes do not get forwarded to original publisher or to other relays, they are instead immediately fulfilled by the first hop relay, which may pull the data from some distributed/localized cache.  It is totally acceptable that fetch based subscribes (aka filter type 0x4), can be in duplicate... although I suspect that is a mistake/error on the client side to request at the same time overlapping/exact same data. Regardless, it's not a big deal for the relay to satisfy this repeated request over the same data at the exact same time, but there needs to be some level of rate limits established to mitigate DoS.  While MOQT doesn't need to define the limits, it does need to support error responses that the limit has exceeded. 

In the case of live stream, IMO it's 100% mistake for any client to ask for the same live stream twice via the same QUIC connection. While talking with @wilaw , he mentioned a possible use-case where there are two or more displays that you want to display the same content to. If the display has IP connectivity, it should be reasonable that the display would have connected and subscribed to the content, hence moot.  In the case where the display does not have IP connectivity, a HUB device could be used that does have IP to act as the MOQT client to receive the data content. IMO, it does not make sense that anyone would want duplicate live feeds of the same data via the same QUIC connection. Instead, if the HUB device has multiple displaces that are not IP connected and cannot make MOQT connections themselves, they likely have some other method to mirror content, such as an HDMI splitter.  I'm interest in hearing the use-cases that require MOQT to directly support and require relays to support duplication of live streams to the same QUIC connection. 


Per discussion with @wilaw , the relay peering would never duplicate the live feeds. It would de-dup all these requests using the track `namespace + name`, regardless of how many track aliases were used by a client subscribe. The original publisher would realize this aggregation/de-duplication.   In other words, each subscribe from the same QUIC connection or from multiple QUIC connections (in theory different clients) would be grouped together by the relay using the `namespace + name`. Each of the `subscribe_id` and `track_alias` values together represent a feed. In this sense, only `subscribe_id` or `track_alias` is needed for this process, not both when considering live feeds.  Again, fetch is different and is distinguished not only by `subscribe_id`, `track_alias`, but also by **start** and **end** **ranges**.

I'm interesting in hearing the use-cases of why MOQT requires of the relay to support  duplicate fetch requests for the exact same ranges at the same time when the other hasn't finished yet.  Seems like it would make sense that if the same QUIC connection (aka client endpoint) request range X - Y and while still sending X - Y, it requests it again, that it would cancel the previous and start over.
