### ISSUE TITLE
QUIC flow control does not map cleanly to MoQ subscriptions

### ISSUE THREAD

**Issue by ianswett** [moq-wg/moq-transport#490]
QUIC flow control doesn't work cleanly with MoQ, because a MoQ subscription can and is typically expected to span multiple streams, and can span multiple subscriptions per session. As a result, neither QUIC's session or stream flow control map cleanly to MoQ subscriptions.

As a contrast, HTTP is a single stream all the way through, and it's possible to exert backpressure, particularly within proxies.

For large requests to a proxy, this creates a challenge, because it can create a number of small range requests, but it doesn't know how large they should be.   The different stream mappings only make this more complex to reason about.  This is one case where stream per subscription/track is trivial.

One possible solution is to have each hop of MoQ decide how to use streams, and if there was a request for a large range that was in the past and subscription was in ascending group order, it could be delivered over a single QUIC stream, at least until it got close to the live edge.

**Comment by suhasHere** [comment]
May be this is a good time to resurrect fetch vs subscribe as well. Some of the fetch semantics can be clearly defined to allow for using only one stream (esp large ranges ), if the relay decides to do so.

Live edge use-cases and old data retrieval use-cases have different requirements and it is bit unfortunate that there is no clean way to separate.

This might also help more carefully define live edge use-cases too and reason about it as the problem space is scoped.

**Comment by vasilvv** [comment]
I agree that there is a difference between flow control for the live data vs flow control for the things that already exist.

Live data in general should not be hitting flow control, since ideally we would discard all of the stale data early enough for us to always fit within the flow control window.

If the data already exists, we do need an end-to-end flow control solution, and putting a fetch on a single stream is probably the easiest answer.

**Comment by ianswett** [comment]
I realized this is very similar to #476

**Comment by fluffy** [comment]
I think the issue here is "how will priority and flow control work when requesting data in the past". Part of the solution will no doubt figure out how to map this streams but when read the title of this issue, it does not seem to be an issue to me.

**Comment by fluffy** [comment]
When requesting a bunch of data from the past, the design questions that come to mind for me are:

Are all the objected delivered over  1 stream or multiple?

How are they prioritized and ordered relative to each other ?

What information is received about objects that have expired ?

How are they prioritized relative to the object flowing on live edge subscriptions. 

At first glance, I tend towards a solutions that puts them over one stream, roughly in group / object order and puts them at a lower priority than live edge subscriptions.

**Comment by afrind** [comment]
Individual Comment:

The issue raised here is still true.  QUIC flow control now cleanly maps to *fetch*, but still not to subscribe.  I'm unsure if relying on timeouts will be sufficient to protect receivers, and think we may revisit this down the line.
