### ISSUE TITLE
Content access protection: transport of authentication tokens

### ISSUE THREAD

**Issue by gwendalsimon** [moq-wg/moq-transport#496]
Tokens are essential elements of security policies. In the current video streaming, the end-user (the one who consumes the content) gets one "individual" token from the Content Owner security system. The end-user sends this token when starting a session (requesting the manifest/playlist); the server process the token to either grant access to the stream or reject it. The token is sent from the client to the server via 1/ cookies, 2/ query parameter, 3/ URL path, 4/ HTTP header.

In MoQ, we would ideally need a token with the subscription message to decide whether an end-user can access a track or not. It looks like none of the 4 options is doable with MOQT. Am I wrong here? Should we add a "token" field in the subscription message to let the client add some authentication parameters, which the relay is expected to process? If so, the token could be a CWT, typically based on CTA-Wave Common Access Token.

**Comment by suhasHere** [comment]
There is Auth Info parameter for this purpose that will be used in Subscribe. The format of it is opaque to keep the token and other  fields specific to the application . iirc from my recollection of weekly calls, security/privacy/authz will be topic of discussions for upcoming interims

**Comment by afrind** [comment]
I think Auth Info is what you want right now.  The group has said they want to revisit auth in more detail but probably after a few other topics are sorted.  Please reopen if you need more in the short term, or have other specific requirements we should consider.
