### ISSUE TITLE
Media Capabilities

### ISSUE THREAD

**Issue by kixelated** [moq-wg/moq-transport#5]
Currently, media capabilities are left up to the application. It's implied that the producer and consumer have negotiated the codec, resolution, max bitrate, etc through an outside source.

Should we add capabilities to the video protocol itself? Is there some existing standard we should leverage? Do capabilities change on the fly, and thus need to be part of the protocol? How do we get new codecs added to the protocol?

**Comment by VMatrix1900** [comment]
This reminds me of [SDP](https://datatracker.ietf.org/doc/html/rfc4566) used in WebRTC. Capabilities negotiation seems like a one-time thing. The producer and consumer negotiate a capability set. Then the producer is free to change the codec, resolution, bitrate within the limit of the negotiated set. The set will not change on the fly, but the exact chosen value may vary from segment to segment.

**Comment by suhasHere** [comment]
We need a way to setup manifest declaratively. But at the media transport layer, all we need is to have a mapping to the capability and media container will have further details

**Comment by fluffy** [comment]
We need something simple that can help make this work. I 100% don't want SDP offer/answer. Way too complicated. But I do want a player to be able understand how to move between varios renditions given the bitrate available and things like that.

**Comment by kixelated** [comment]
Suhas and I chatted about this quite a bit in person.

There's quite a bit of overlap between announcing capabilities (ex. I support h.264 or VP9) and announcing available tracks (ex. you can choose the language/rendition).

The sender could just announce h.264 and VP9 as separate tracks and start encoding when first requested. I think that's how SDP works?

We would have to be careful about introducing too many permutations. For example, every combination of possible container, codec, resolution, bitrate, etc.
