### ISSUE TITLE
Simplify naming by removing the distinction between Track Namespace and Track Name

### ISSUE THREAD

**Issue by wilaw** [moq-wg/moq-transport#508]
Alan's PR https://github.com/moq-wg/moq-transport/pull/498 introduced a N-tuple construct for namespace, in which the namespace is made up of an ordered sequence of between 1 - 32 byte arrays. This allows us to construct namespaces in the form

`example.com` `meeting` `abc123` `alice`

Alice would publish tracks under this namespace called audio|video|catalog leading to the final track identifiers being

`example.com` `meeting` `abc123` `alice` `audio`
`example.com` `meeting` `abc123` `alice` `video`
`example.com` `meeting` `abc123` `alice` `catalog`

At this point, the distinction between the track name and last stanza of the namespace is arbitrary and I would argue, unnecessary.

We could remove the separate concepts of TRACK-NAMESPACE and TRACK-NAME and instead coalesce this down to a single construct of TRACK-NAME, which would hold the same definition as a bounded N-tuple. So under the simplified scheme, the TRACK-NAMES would be 

`example.com` `meeting` `abc123` `alice` `audio`
`example.com` `meeting` `abc123` `alice` `video`
`example.com` `meeting` `abc123` `alice` `catalog`

Alice as the publisher would ANNOUNCE the _minimum prefix_ which uniquely describes describes the content she is responsible for, in this case, she would announce

`example.com` `meeting` `abc123` `alice`

This schema then allows for easy aggregate subscription. We could remove the need for SUBSCRIBE-NAMESPACE. For example, a subscriber wanting to receive everything produced by Alice would SUBSCRIBE  to 

`example.com` `meeting` `abc123` `alice`

Someone wanting to receive all feeds from meeting abc123 would SUBSCRIBE to

`example.com` `meeting` `abc123`

If we standardize some means of communicating a null (*) stanza, and if different publishers produced

`example.com` `meeting` `abc123`
`statistics.com` `metrics` `abc123`

the someone wanting both the meeting and metrics for abc123 could SUBSCRIBE to 

`    ` `    ` `abc123`

**Comment by suhasHere** [comment]
I generally like the suggestion here except the  last <null> <null> abc123.  If we allow nulls or (.*) regex parsing in between , it just makes things pretty slow.  We can start with prefix matching to begin with,

**Comment by alvestrand** [comment]
Having complete names from the name root to the tree node you want to point
to is usually a Good Thing (experience with DNS searchpaths).
If nulls were allowed, subscribing to "foo" would result in "mallory foo"
popping up in your feed when you just wanted to listen to "alice foo" and
"bob foo", with no knowledge ahead of time that Mallory existed.

**Comment by suhasHere** [comment]
> Having complete names from the name root to the tree node you want to point to is usually a Good Thing (experience with DNS searchpaths).

+1

**Comment by ianswett** [comment]
I started working on a PR to do a simple version of this that merged the two fields, and it was more invasive than I was expecting.  One question is what to call the new single field.  "Track Name" or "Full Track Name"?

**Comment by wilaw** [comment]
> One question is what to call the new single field. "Track Name" or "Full Track Name"?

Just "Track name". There is no longer any notion of "full".

**Comment by afrind** [comment]
Individual Comment:

The primary reason to *retain* the distinction is that it makes it unambiguous that SUBSCRIBE is *always* for a single track.  If we merged namespace and name into a single entity, then it becomes possible to SUBSCRIBE to a namespace (eg Wildcard Subscribe, see #253 and #615).  If we merge namespace and name but don't add Wildcard Subscribe, we need normative language (and maybe an error code) to indicate that a publisher MUST reject a subscribe if it doesn't unambiguously name a single track.  If we decide to add Wildcard Subscribe, then a merge makes total sense.

Irrespective, in the current design perhaps ANNOUNCE is too restrictive, and should have an optional Track Name field.  This would make it possible to ANNOUNCE a single track.

**Comment by wilaw** [comment]
Discussed at Boston interim. Notes below. No consensus to proceed to PR. 

> 14:30 Track Namespace + Name merge, and Wildcard Subscribe - Will
> Cullen: Empty gaps in the middle of the name tuples should not be
> allowed.
> Luke: How does a relay know a name is a wildcard to avoid forwarding
> upstream?
> Will: Relays know what was announced and published, so they know
> wildcard vs published track.
> Mike: Sees value in wildcard in the middle.
> Victor: Wary of wildcard subscribe due to track state.
> Daniel: Also wary of wildcard subscribe.
> Mo: Wildcard subscribe should be supported via subscribe announce, then
> subsequent subscribes to each desired track after seeing each
> announced/published track.
> Ian: Sees a lot of work and complexity in wildcard subscribe.
> Suhas: Details of how the wildcard subscribe mechanism work need to be
> designed, but should not stop the need and progress.
> Chairs: ==No consensus to merge track namespace and name into tuples or
> wildcard subscribe.==
