### ISSUE TITLE
Subscribe with time offset

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#52]
It would be good if a subscriber can specify he is interested to in the media being sent starting from a given time offset

For the first phase, we can keep it focussed on time offsets that is closer to live edge and may be expand eventually to support DVR like long running time offsets.

**Comment by kixelated** [comment]
side note; I'd like to see this use the presentation timestamp instead of the GoP sequence number. It should be possible to use an absolute timestamp (ex. 3:12) and a relative timestamp (ex. 5s before live).

**Comment by afrind** [comment]
@suhasHere : this is kind of an old issue, has it beed overtaken by events?  The current draft allows for subscribing against track, track+group, or track+object+group.  There is also a generic Track Parameters struct in the SUBSCRIBE REQUEST that would allow for extensions, such as querying by Timestamp *if* the publisher supported that.
