### ISSUE TITLE
Why define a boolean type but be lenient with its usage?

### ISSUE THREAD

**Issue by LPardue** [moq-wg/moq-transport#542]
https://moq-wg.github.io/moq-transport/draft-ietf-moq-transport.html#section-1.3-5.4.1 states 

> Indicates that x is a flag and is encoded as a single byte with the value 0 or 1. A value of 0 indicates the flag is false or off, while a value of 1 indicates the flag is true or on. Any other value is a protocol error and SHOULD terminate the session with a Protocol Violation ([Section 3.5](https://moq-wg.github.io/moq-transport/draft-ietf-moq-transport.html#session-termination)).

This seems at odds with the QUIC design ethos of being very strict about receiving things that are obviously broken. This matter is wrapped up in https://github.com/moq-wg/moq-transport/issues/536 and the proposed change (https://github.com/moq-wg/moq-transport/pull/543), so I wanted to track the question separately.

I suspect we might want a bigger pass over the recomendations about when to detect a protocol error and how to handle it but I don't want to miss this specific issue in case it was done for a good reason.

**Comment by LPardue** [comment]
I don't think this is editorial, since it affects the expectations on what a receiver is expected to do

**Comment by ianswett** [comment]
To clarify, the proposal is to change the SHOULD terminate to a MUST terminate?

I expect that's what everyone will do anyway, so this SG

**Comment by LPardue** [comment]
Yes that would be my proposal here.

And in addition, a separate review of other fields for consistency.

**Comment by LPardue** [comment]
Discussed in today's interim. MUST rolled into https://github.com/moq-wg/moq-transport/pull/543 and merged. So closing issue as done.
