### ISSUE TITLE
Is a namespace tuple with >32 elements a protocol violation?

### ISSUE THREAD

**Issue by DanielFay22** [moq-wg/moq-transport#551]
Current definition specifies namespace is an N-tuple, with 1<=N<=32. If the server/relay receives a namespace with N>32 is it expected to return a protocol violation, or do we leave that undefined?

**Comment by LPardue** [comment]
+1 I think we should address this as part of refactoring the tuple type

**Comment by afrind** [comment]
I put up a PR addressing the issue but didn't do a larger refactor of the tuple type, which seems editorial.
