### ISSUE TITLE
Why does OBJECT_DATAGRAM have a length?

### ISSUE THREAD

**Issue by afrind** [moq-wg/moq-transport#552]
In previous drafts, the payload ran to the end of the transport datagram.  This length adds 1 or 2 bytes, and creates error conditions.

**Comment by ianswett** [comment]
I believe this was an error, and not intentional?

**Comment by afrind** [comment]
The current function of length is that if it is 0, then Status is present and payload is not, which is also how it works in streams.  So there's a tradeoff of having it be similar to other object encodings, vs not having a length and accomplishing the flag behavior a different way.

**Comment by fluffy** [comment]
@suhasHere thoughts ????

**Comment by fluffy** [comment]
Seems like it might have just been oversight to add this.
