### ISSUE TITLE
Slice as segment

### ISSUE THREAD

**Issue by ZmGorynych** [moq-wg/moq-transport#57]
In some ultra low latency use cases a video frame is encoded in multiple slices (which are independently decodable complete NAL units) and the upper slices are ready earlier than the ones on the bottom. In case of gradual decoder refresh, some slices may be intra-coded and some can be inter-coded.
A frequent optimization is to send slices as they are ready as opposed to waiting till the end of the frame. It looks like this use case is not supported in the draft

**Comment by suhasHere** [comment]
@ZmGorynych  I have also been thinking around some of these application specific grouping in next generation use-cases like (AR/VR) and have been playing around with  a data model that might help in this situation .. 

I will get back here once I have something written

**Comment by kixelated** [comment]
Yeah, I think breaking the media into slices will eventually be necessary. I don't have much experience with gradual decoder refresh but it makes a ton of sense for smoothing out IDR bitrate spike.

**Comment by acbegen** [comment]
I suppose the subject should be "slice as a stream" and this will certainly make sense in certain low-latency apps, especially in interactive ones.

**Comment by suhasHere** [comment]
@ZmGorynych, does the proposed update help  #69  . I have seem many low latency use-cases needing sort of grouping this issue raises

**Comment by huitema** [comment]
I think it would be just fine to encode each slice as a separate object, and use metadata to manage transmission order, priorities, etc. For example, upper slices would be marked at higher priority than slices with fine details, and would be sent first. In case of congestion, relays might drop the details.

**Comment by fluffy** [comment]
I agree an applications should be able to choose to do an object per slice.  If a slice is lost, some video devices want to display the rest of the frame that was received. Some application choose not to show the whole frame if any part of it was not received. I think that should be an application choice and it would probably change how the application decided to to put slices or full frames into single objects.

**Comment by suhasHere** [comment]
moq-usages draft address some of the discussions around such an encoding. Agree with @ianswett , this is application defined and not specific to MOQT.
