### ISSUE TITLE
Do we need the Role parameter

### ISSUE THREAD

**Issue by fluffy** [moq-wg/moq-transport#574]
Not clear what the use case is. Seems like a foot gun in that it can be set wrong for how the connection is used.

**Comment by fluffy** [comment]
I don't care if we leave it or keep it. Just adding this as I got questions about why have it.

**Comment by wilaw** [comment]
Having the client voluntarily declare itself to abide by a certain role is not preventing the relay form having to do any work. A  malicious client will declare one role but then act differently. Any relay open to the public has to protect itself against unauthorized ANNOUNCE and SUBSCRIBE control messages, irrespective of what role was declared. Therefore the upfront role declaration is superfluous.

**Comment by ianswett** [comment]
I tend to agree it's not doing anything helpful here, and sent out #603 to remove it.
