### ISSUE TITLE
What parameters go in FETCH and FETCH_OK?

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#594]
Section 6.1.1 has not been updated to reflect the 2 new messages with parameters.

**Comment by ianswett** [comment]
I don't have a strong preference.  Mind writing up a PR of whatever you think is a sensible proposal?

**Comment by suhasHere** [comment]
I can think of AuthInfo as the only parameter that makes sense for now. @martinduke   please let me know if you think of anything else. I can add it to my PR. Thanks
