### ISSUE TITLE
Why does track namespace limit into 32 bytes?

### ISSUE THREAD

**Issue by tyqu-cisco** [moq-wg/moq-transport#614]
"Track namespace is an ordered N-tuple of bytes where N can be between 1 and 32." For one online conferences application, we use uuid to identify the different conferences, this namespace can meet online conference requirements.

**Comment by wilaw** [comment]
There is no byte limit currently specified for the N-32 tuple. The limit is that the tuple can at most be comprised of 32 elements.  So you could place a UUID into the first element of the tuple, or shard you uuid across the first 5 elements. You could even have 32 uuids,  one in each element of the tuple.
