### ISSUE TITLE
QUIC is over UDP

### ISSUE THREAD

**Issue by martinduke** [moq-wg/moq-transport#73]
In Sec 3.1 it says "This is possible with the emergence of QUIC, designed to fix the shortcomings of TCP" in the context of TCP and UDP-based protocols.

Pedants will note that QUIC is over UDP. It is probably worth to add something to the effect of:

"While QUIC is also over UDP, it frees the media protocol from handling functions that might otherwise be handled by TCP."

**Comment by afrind** [comment]
This section now reads:

> TCP-based protocols are simple but are slow to detect congestion and suffer from head-of-line blocking. UDP-based protocols can avoid queuing, but the application is now responsible for the complexity of fragmentation, congestion control, retransmissions, receiver feedback, reassembly, and more. One goal of MOQT is to achieve the best of both these worlds: leverage the features of QUIC to create a simple yet flexible low latency protocol that can rapidly detect and respond to congestion

Not sure if that fully addressed your concern @martinduke

**Comment by martinduke** [comment]
Not really. It's a minor point, but how about
s/UDP-based protocols/protocols directly over UDP
