### ISSUE TITLE
Definition of Messages in Section  makes too many assumptions

### ISSUE THREAD

**Issue by huitema** [moq-wg/moq-transport#78]
I am concern that the definition of messages in section 6 relies too much on a specific way to organize the application, i.e., the "catalog". My experience building the QUICR prototype tells me that a much simpler design is possible:

1) Applications are designed to handle a number of media streams, organizing these media streams as a set of media streams possibly coming from multiple sources, e.g., multiple participants in a video conference. But then, some applications will have different designs, e.g., just one single broadcast source. The "catalog" is an attempt to advertise and organize these multiple streams, but it is pretty hard to do that in a fully generic way. It might be much simpler to punt, and decide that QUICR will only specify the transport of exactly one media stream, identified by a unique URI. That means, removing the "catalog".

2) The current protocol (WARP) specifies organizing the media stream as a set of "group of objects". This should be reflected in the protocol messages.

3) Implementations would be simpler if the transport definitions were split for each media stream between a "bidirectional QUIC control stream" carrying setup messages and a set of "unidirectional QUIC data streams" (or possibly, datagrams). This can negotiate a media ID (e.g., the stream ID of the control stream), making the object headers significantly shorter.

4) WARP stream would be better defined as composed of a WARP header (media ID, group ID, some group parameters) followed by series of object in the group -- no need then to repeat media ID and group ID for each object.

5) We should pay more attention to termination conditions, e.g. specify how many objects were expected in a given block, or what is the last object of a media stream. This is useful to detect error conditions, monitor losses, etc. Also, allows termination of streams "as soon as everything is received", instead of waiting for time outs.

**Comment by suhasHere** [comment]
I think this issue is still valid and address with some of the recent alignments and changes that went in or proposed

**Comment by ianswett** [comment]
I believe this is OBE, but reopen or open new more focused issues if I'm wrong.
