### ISSUE TITLE
Relay failover support for subscribers and publishers

### ISSUE THREAD

**Issue by suhasHere** [moq-wg/moq-transport#80]
There is a need for subscribers and publishers to reconnect across relays with minimal state loss.

**Comment by kixelated** [comment]
Yeah, that means limiting the amount of per-connection state. As was mentioned at lunch, we could still use something like QPACK to compress on a per-connection state, but stuff like the broadcast URN should be consistent across connections.

**Comment by afrind** [comment]
I think this is a duplicate of #79, which is more generic (the reconnect problem applies to all publishers/subscribers and not just relays)

**Comment by afrind** [comment]
Closed it too quickly, that issue is only about publishers.

**Comment by suhasHere** [comment]
yes, this needs some handling in the transport

**Comment by ianswett** [comment]
There are newer issues that discuss this in more detail, so closing this as a duplicate.
