### ISSUE TITLE
Failover strategy when QUIC is unavailable

### ISSUE THREAD

**Issue by hardie** [moq-wg/moq-transport#88]
Issue raised at interim on Feb 1, 2023:

Does the protocol need to define a failover if QUIC is not available on a specific path.  If so, is it the same failover in all cases?

**Comment by vasilvv** [comment]
Note that WebTransport does provide a failover to HTTP/2.

**Comment by suhasHere** [comment]
We need a answer for Raw QUIC too

**Comment by fluffy** [comment]
We discussed this in chartering and came down on a hard no. It just makes things too complicated. Yep, the webtransport version of it might work fine on TCP and we are not out to break that but it is not a design goal. This is about media over QUIC and QUIC is over UDP. 

The CDNs may internally do whatever they do but that is a black box.

**Comment by ianswett** [comment]
I agree that this is out of scope, based on my reading of the charter, which says "can be used over raw QUIC or WebTransport."

I would like to either close with no action or we can add editorial text that notes that all paths may not support QUIC.

**Comment by ianswett** [comment]
It was decided that a sentence or two about this, including a note that the appropriate fallback may be something entirely different from MoQ (ie: DASH/HLS/etc) depending upon the application and deployment.
